"use strict";

const NEPTUNE_TEXTURE = "assets/textures/neptune-atmosphere-4k.jpg";
const NEPTUNE_CLOUDS = "assets/textures/neptune-clouds-4k.png";
const NEPTUNE_BUMP = "assets/textures/neptune-cloud-bump-2k.jpg";
const NEPTUNE_TRITON_TEXTURE = "assets/textures/triton-2k.jpg";
const NEPTUNE_URANUS_TEXTURE = "assets/textures/uranus-atmosphere-4k.jpg";
const NEPTUNE_TILT_DEG = 28.32;
const NASA_NEPTUNE_GLOBAL = "https://science.nasa.gov/wp-content/uploads/2023/06/neptune-pia01492-1920x640-2-jpg.webp?w=1536";
const NASA_NEPTUNE_STORM = "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00052/PIA00052.jpg?crop=faces%2Cfocalpoint&fit=clip&h=852&w=700";
const NASA_NEPTUNE_RINGS = "https://images-assets.nasa.gov/image/PIA01493/PIA01493~orig.jpg";
const NASA_TRITON = "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia02/pia02211/PIA02211.jpg?crop=faces%2Cfocalpoint&fit=clip&h=795&w=795";

const NEPTUNE_EXPLORATION_STOPS = Object.freeze([
  {
    kicker:"IDENTITAS NEPTUNUS", title:"Dunia Biru di Batas Planet", subtitle:"Planet kedelapan dan planet mayor terjauh dari Matahari",
    summary:"Neptunus adalah planet kedelapan dan planet mayor terjauh dari Matahari. Ia termasuk raksasa es, memiliki atmosfer biru berawan, sistem cincin redup, serta cuaca yang jauh lebih aktif daripada penampilannya dari kejauhan.",
    facts:["Diameter Neptunus sekitar 49.528 km.","Jarak rata-rata dari Matahari sekitar 30 AU atau 4,5 miliar km.","Satu tahun Neptunus berlangsung sekitar 165 tahun Bumi."],
    source:"https://science.nasa.gov/neptune/neptune-facts/", semantic:"identity",
    images:[
      {src:"./assets/neptune-identity-diagram.svg",alt:"Diagram identitas Neptunus sebagai planet kedelapan",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/neptune/neptune-facts/",caption:"Neptunus, planet kedelapan dan dunia raksasa es",fit:"contain"},
      {src:NASA_NEPTUNE_GLOBAL,alt:"Neptunus dipotret Voyager 2 dengan awan dan atmosfer biru",credit:"NASA/JPL-Caltech · Voyager 2",source:"https://science.nasa.gov/neptune/",caption:"Neptunus dalam citra Voyager 2",fit:"contain"}
    ]
  },
  {
    kicker:"DUNIA RAKSASA ES", title:"Bukan Lautan Biru Padat", subtitle:"Fluida panas dan padat berada jauh di bawah atmosfer",
    summary:"Sebutan raksasa es tidak berarti Neptunus adalah bola es beku. Sebagian besar massanya berada dalam lapisan fluida panas dan padat yang kaya air, metana, dan amonia di atas inti yang lebih padat.",
    facts:["Neptunus tidak memiliki permukaan padat tempat wahana dapat mendarat.","Material interior berada pada tekanan dan suhu yang sangat tinggi.","Strukturnya berbeda dari raksasa gas Jupiter dan Saturnus."],
    source:"https://science.nasa.gov/neptune/neptune-facts/", semantic:"interior",
    images:[{src:"./assets/neptune-interior-diagram.svg",alt:"Diagram konseptual interior Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/neptune/neptune-facts/",caption:"Lapisan konseptual interior raksasa es",fit:"contain"}]
  },
  {
    kicker:"ATMOSFER METANA", title:"Biru yang Datang dari Atmosfer", subtitle:"Hidrogen, helium, metana, haze, dan awan membentuk lapisan yang kompleks",
    summary:"Atmosfer Neptunus terutama tersusun dari hidrogen dan helium, dengan metana yang menyerap cahaya merah. Warna planet juga dipengaruhi oleh proses atmosfer dan aerosol yang masih dipelajari.",
    facts:["Metana menyerap panjang gelombang merah pada cahaya yang masuk.","Atmosfer memperlihatkan pita, haze, badai, dan awan tinggi yang berubah.","Warna presentasi ANTARA dibuat lebih kontras untuk keterbacaan tetapi tetap dijaga agar tidak menjadi biru neon."],
    source:"https://science.nasa.gov/neptune/neptune-facts/", semantic:"atmosphere",
    images:[{src:"./assets/neptune-atmosphere-diagram.svg",alt:"Diagram atmosfer metana Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/neptune/neptune-facts/",caption:"Lapisan atmosfer Neptunus",fit:"contain"}]
  },
  {
    kicker:"ANGIN EKSTREM", title:"Atmosfer yang Melaju Sangat Cepat", subtitle:"Awan memanjang menandai aliran atmosfer yang luar biasa kuat",
    summary:"Neptunus memiliki angin tercepat yang pernah diukur pada planet di Tata Surya. Beberapa aliran atmosfer mencapai sekitar 2.000 km per jam, jauh melampaui badai terkuat di Bumi.",
    facts:["Banyak angin Neptunus bergerak berlawanan arah dengan rotasi planet.","Kecepatan dan arah angin berubah menurut lintang.","Awan memanjang dan streak membantu memperlihatkan struktur aliran atmosfer."],
    source:"https://science.nasa.gov/mission/voyager/fact-sheet/", semantic:"winds",
    images:[{src:"./assets/neptune-winds-diagram.svg",alt:"Diagram aliran angin cepat di atmosfer Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA Voyager",source:"https://science.nasa.gov/mission/voyager/fact-sheet/",caption:"Aliran atmosfer Neptunus dapat mencapai sekitar 2.000 km/jam",fit:"contain"}]
  },
  {
    kicker:"BADAI BESAR", title:"Sistem Badai yang Datang dan Pergi", subtitle:"Fitur gelap adalah fenomena atmosfer, bukan lokasi geologi permanen",
    summary:"Voyager 2 pernah mengamati Great Dark Spot, sebuah sistem badai besar dengan awan putih terang di sekitarnya. Pengamatan kemudian menunjukkan bahwa fitur gelap besar dapat berubah atau menghilang dan badai baru dapat terbentuk.",
    facts:["Great Dark Spot yang dilihat Voyager 2 tidak dianggap sebagai tanda permanen pada planet.","Awan putih tinggi dapat terbentuk di sekitar batas badai.","Struktur spiral dan awan cirrus membantu menunjukkan rotasi sistem badai."],
    source:"https://science.nasa.gov/photojournal/neptune-great-dark-spot-in-high-resolution/", semantic:"storm",
    images:[
      {src:NASA_NEPTUNE_STORM,alt:"Great Dark Spot Neptunus dengan awan putih di sekitarnya",credit:"NASA/JPL · Voyager 2 · PIA00052",source:"https://science.nasa.gov/photojournal/neptune-great-dark-spot-in-high-resolution/",caption:"Great Dark Spot dan awan tinggi di sekitarnya",fit:"contain"},
      {src:"./assets/neptune-storm-diagram.svg",alt:"Diagram sistem badai atmosfer Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA/JPL",source:"https://science.nasa.gov/photojournal/neptune-great-dark-spot-in-high-resolution/",caption:"Badai Neptunus adalah sistem atmosfer yang dapat berevolusi",fit:"contain"}
    ]
  },
  {
    kicker:"AWAN METANA", title:"Awan Putih di Atas Dunia Biru", subtitle:"Fitur terang berada tinggi di atmosfer dan berubah dalam waktu singkat",
    summary:"Neptunus memperlihatkan awan putih terang yang dapat berada pada ketinggian lebih tinggi daripada lapisan awan biru di bawahnya. Bentuknya memanjang dan dapat berubah dengan cepat mengikuti dinamika atmosfer.",
    facts:["Awan terang membantu memperlihatkan kecepatan dan arah aliran atmosfer.","Beberapa awan tinggi tampak seperti cirrus yang memanjang.","Kontras putih dan biru membuat atmosfer Neptunus terlihat lebih aktif daripada Uranus."],
    source:"https://science.nasa.gov/mission/voyager/fact-sheet/", semantic:"clouds",
    images:[{src:"./assets/neptune-clouds-diagram.svg",alt:"Diagram awan tinggi Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA Voyager",source:"https://science.nasa.gov/mission/voyager/fact-sheet/",caption:"Awan terang pada atmosfer Neptunus",fit:"contain"}]
  },
  {
    kicker:"CINCIN NEPTUNUS", title:"Lima Cincin Utama yang Redup", subtitle:"Sistem cincin tipis, berdebu, dan jauh lebih sulit dilihat daripada Saturnus",
    summary:"Neptunus memiliki setidaknya lima cincin utama. Cincin-cincinnya gelap dan redup, sementara cincin Adams memuat busur material yang kepadatannya tidak merata.",
    facts:["Lima cincin utama bernama Galle, Leverrier, Lassell, Arago, dan Adams.","Empat busur terkenal di cincin Adams bernama Liberté, Egalité, Fraternité, dan Courage.","Cincin Neptunus mengandung banyak partikel debu dan tetap jauh lebih redup daripada cincin Saturnus."],
    source:"https://science.nasa.gov/neptune/neptune-facts/", semantic:"rings",
    images:[
      {src:NASA_NEPTUNE_RINGS,alt:"Cincin dan busur Neptunus dipotret Voyager 2",credit:"NASA/JPL · Voyager 2 · PIA01493",source:"https://science.nasa.gov/image-detail/amf-pia01493/",caption:"Cincin luar Neptunus dan material yang menggumpal menjadi busur",fit:"contain"},
      {src:"./assets/neptune-rings-diagram.svg",alt:"Diagram cincin utama dan busur Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/neptune/neptune-facts/",caption:"Lima cincin utama dan busur di cincin Adams",fit:"contain"}
    ]
  },
  {
    kicker:"TRITON", title:"Bulan Besar yang Bergerak Terbalik", subtitle:"Orbit retrograde memberi petunjuk bahwa Triton kemungkinan merupakan objek yang tertangkap",
    summary:"Triton adalah bulan terbesar Neptunus dan salah satu dunia es paling menarik di Tata Surya. Ia mengorbit berlawanan arah dengan rotasi Neptunus, perilaku yang mendukung gagasan bahwa Triton dahulu merupakan objek mandiri yang kemudian tertangkap.",
    facts:["Diameter Triton sekitar 2.700 km.","Triton adalah satu-satunya bulan besar yang mengorbit planetnya secara retrograde.","Voyager 2 melihat aktivitas geyser dan plume pada permukaan Triton yang sangat dingin."],
    source:"https://science.nasa.gov/neptune/moons/triton/", semantic:"triton",
    images:[
      {src:NASA_TRITON,alt:"Triton dipotret Voyager 2",credit:"NASA/JPL · Voyager 2 · PIA02211",source:"https://science.nasa.gov/photojournal/triton-2/",caption:"Triton dalam citra Voyager 2",fit:"contain"},
      {src:"./assets/neptune-triton-diagram.svg",alt:"Diagram orbit retrograde Triton terhadap Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/neptune/moons/triton/",caption:"Triton mengorbit berlawanan arah dengan rotasi Neptunus",fit:"contain"}
    ]
  },
  {
    kicker:"MEDAN MAGNET", title:"Magnetosfer yang Miring dan Bergeser", subtitle:"Medan magnet Neptunus tidak sederhana atau terpusat",
    summary:"Medan magnet Neptunus sangat miring terhadap sumbu rotasi dan bergeser dari pusat fisik planet. Pola ini memiliki kemiripan dengan Uranus dan memberi petunjuk tentang dinamika interior kedua raksasa es.",
    facts:["Sumbu magnet Neptunus miring sekitar 47 derajat terhadap sumbu rotasi.","Pusat medan magnet bergeser jauh dari pusat fisik planet.","Voyager 2 juga mendeteksi aurora yang lebih lemah daripada aurora Bumi."],
    source:"https://science.nasa.gov/mission/voyager/fact-sheet/", semantic:"magnetosphere",
    images:[{src:"./assets/neptune-magnetosphere-diagram.svg",alt:"Diagram medan magnet Neptunus yang miring",credit:"Visualisasi ANTARA berdasarkan NASA Voyager",source:"https://science.nasa.gov/mission/voyager/fact-sheet/",caption:"Magnetosfer Neptunus miring dan tidak terpusat",fit:"contain"}]
  },
  {
    kicker:"VOYAGER 2", title:"Pertemuan Dekat Pertama dan Satu-satunya", subtitle:"Flyby 1989 membuka pandangan pertama kita terhadap dunia terjauh ini",
    summary:"Pada 25 Agustus 1989, Voyager 2 terbang dekat Neptunus dan menjadi satu-satunya wahana yang pernah mengunjungi planet ini dari dekat. Data flyby mengungkap angin ekstrem, cincin, medan magnet, badai, dan dunia Triton.",
    facts:["Voyager 2 melintas sekitar 4.800 km di atas puncak awan Neptunus.","Flyby menemukan enam bulan baru dan empat cincin baru pada saat itu.","Sepuluh instrumen Voyager 2 masih berfungsi saat pertemuan Neptunus."],
    source:"https://science.nasa.gov/mission/voyager/voyager-2/", semantic:"voyager",
    images:[{src:"./assets/neptune-voyager-diagram.svg",alt:"Diagram Voyager 2 melintasi Neptunus",credit:"Visualisasi ANTARA berdasarkan NASA/JPL",source:"https://science.nasa.gov/mission/voyager/voyager-2/",caption:"Voyager 2 · flyby Neptunus, 25 Agustus 1989",fit:"contain"}]
  },
  {
    kicker:"PLANET MAYOR TERLUAR", title:"Akhir Urutan Delapan Planet, Bukan Akhir Tata Surya", subtitle:"Di luar Neptunus masih terbentang wilayah trans-Neptunus",
    summary:"Neptunus menutup urutan delapan planet mayor dalam perjalanan ANTARA. Namun Tata Surya tidak berhenti di sini. Di luar orbitnya terdapat Sabuk Kuiper, planet katai, objek trans-Neptunus, dan wilayah yang jauh lebih luas.",
    facts:["Neptunus adalah planet kedelapan dan planet mayor terjauh dari Matahari.","Sabuk Kuiper berada di luar orbit Neptunus dan berisi banyak benda kecil serta planet katai.","Perjalanan planet selesai di Neptunus, tetapi lingkungan Tata Surya berlanjut jauh setelahnya."],
    source:"https://science.nasa.gov/neptune/", semantic:"final",
    images:[{src:"./assets/neptune-final-diagram.svg",alt:"Diagram Neptunus sebagai planet mayor terluar dengan wilayah trans-Neptunus di luar orbitnya",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/neptune/",caption:"Neptunus menutup urutan delapan planet mayor",fit:"contain"}]
  }
]);

window.NeptuneScene = class NeptuneScene {
  constructor(){
    this.element=document.getElementById("neptune-scene"); this.viewport=document.getElementById("neptune-viewport"); this.caption=this.element.querySelector(".neptune-caption");
    this.title=document.getElementById("neptune-title"); this.exploreButton=document.getElementById("neptune-explore-button"); this.exploration=document.getElementById("neptune-exploration"); this.explorationClose=document.getElementById("neptune-exploration-close");
    this.topicKicker=document.getElementById("neptune-topic-kicker"); this.topicTitle=document.getElementById("neptune-topic-title"); this.topicSubtitle=document.getElementById("neptune-topic-subtitle"); this.topicSummary=document.getElementById("neptune-topic-summary"); this.topicFacts=document.getElementById("neptune-topic-facts"); this.topicSource=document.getElementById("neptune-topic-source"); this.topicCurrent=document.getElementById("neptune-topic-current"); this.topicTotal=document.getElementById("neptune-topic-total"); this.topicPrev=document.getElementById("neptune-topic-prev"); this.topicNext=document.getElementById("neptune-topic-next"); this.topicProgress=document.getElementById("neptune-topic-progress"); this.contextMedia=document.getElementById("neptune-context-media"); this.credit=this.element.querySelector(".neptune-credit");
    this.ringAnnotation=document.getElementById("neptune-ring-annotation"); this.stormAnnotation=document.getElementById("neptune-storm-annotation"); this.windOverlay=document.getElementById("neptune-wind-overlay"); this.endBadge=document.getElementById("neptune-end-badge");
    this.motion=matchMedia("(prefers-reduced-motion: reduce)"); this.loading=null; this.mode="pending"; this.active=false; this.exploring=false; this.topicIndex=0; this.explorationBlend=0; this.explorationBlendTarget=0; this.frame=null; this.previous=0; this.time=0; this.renderedRotation=-1.90; this.rotationBase=-1.90;
    this.width=1; this.height=1; this.mobile=false; this.pointer={x:0,y:0}; this.cameraOffset={x:0,y:0}; this.travelMode=null; this.travelDirection=1; this.travelCallbacks={}; this.travelStartedAt=0; this.travelDuration=8.3; this.travelCoveredFired=false; this.travelCompleteFired=false; this.focusState="IDLE_ROTATION"; this.focusProgress=1; this.focusFrom={yaw:-.42,z:7.0}; this.focusTo={yaw:-.42,z:7.0}; this.viewYaw=-.42; this.viewCameraZ=7.0;
    this._uranusVisualOwner=null; this._borrowedUranus=false; this._uranusStartRotation=2.15; this._uranusTimeStart=8.5; this._uranusEndRotation=null; this._uranusEndTime=null; this._uranusVisualTime=8.5;
    this.topicTotal.textContent=String(NEPTUNE_EXPLORATION_STOPS.length).padStart(2,"0"); this.topicProgress.replaceChildren(...NEPTUNE_EXPLORATION_STOPS.map(()=>document.createElement("span"))); this.setExplorationStop(0,{immediate:true,announce:false});
    this.exploreButton.addEventListener("click",()=>this.enterExploration()); this.explorationClose.addEventListener("click",()=>this.exitExploration()); this.topicPrev.addEventListener("click",()=>this.setExplorationStop(this.topicIndex-1)); this.topicNext.addEventListener("click",()=>this.setExplorationStop(this.topicIndex+1));
    this.element.addEventListener("pointermove",e=>{if(e.pointerType!=="mouse"||this.motion.matches||this.travelMode)return;const r=this.element.getBoundingClientRect();this.pointer.x=(e.clientX-r.left)/r.width-.5;this.pointer.y=(e.clientY-r.top)/r.height-.5;}); this.element.addEventListener("pointerleave",()=>{this.pointer.x=this.pointer.y=0;});
    addEventListener("resize",()=>{if(this.active||!this.element.hidden)this.resize();}); document.addEventListener("visibilitychange",()=>{if(!document.hidden&&this.active&&!this.frame){this.previous=performance.now();this.tick(this.previous);}});
  }
  clamp(v,a=0,b=1){return Math.min(b,Math.max(a,v));}
  travelSmooth(v){const t=this.clamp(v);return t*t*t*(t*(t*6-15)+10);}
  loadImage(src){return new Promise((res,rej)=>{const im=new Image();im.decoding="async";im.onload=async()=>{try{await im.decode?.();}catch(_){}res(im);};im.onerror=()=>rej(new Error(`Unable to load ${src}`));im.src=src;});}
  travelState(){const elapsed=this.time-this.travelStartedAt,progress=this.travelSmooth(elapsed/this.travelDuration),pullback=this.travelSmooth(progress/.31),pan=this.travelSmooth((progress-.23)/.39),approach=this.travelSmooth((progress-.58)/.42);return{elapsed,progress,pullback,pan,approach};}
  prepare(){if(this.loading)return this.loading;this.loading=Promise.allSettled([import("./assets/vendor/three/three.module.min.js"),this.loadImage(NEPTUNE_TEXTURE),this.loadImage(NEPTUNE_CLOUDS),this.loadImage(NEPTUNE_BUMP),this.loadImage(NEPTUNE_TRITON_TEXTURE),this.loadImage(NEPTUNE_URANUS_TEXTURE)]).then(async([mod,surface,clouds,bump,triton,uranus])=>{this.surface=surface.status==="fulfilled"?surface.value:this.makeFallbackSurface();this.cloudSurface=clouds.status==="fulfilled"?clouds.value:null;this.bumpSurface=bump.status==="fulfilled"?bump.value:null;this.tritonSurface=triton.status==="fulfilled"?triton.value:null;this.uranusSurface=uranus.status==="fulfilled"?uranus.value:null;if(mod.status==="fulfilled"){try{this.createThreeScene(mod.value);}catch(e){console.warn("Neptune WebGL unavailable; using Canvas fallback.",e);this.createCanvasFallback();}}else this.createCanvasFallback();this.resize();if(this.renderer?.compileAsync)await this.renderer.compileAsync(this.scene,this.camera);this.element.dataset.ready="true";if(this.active)this.render();}).catch(e=>{console.error("Neptune preparation failed",e);this.surface=this.surface||this.makeFallbackSurface();this.createCanvasFallback();this.resize();this.element.dataset.ready="fallback";});return this.loading;}
  makeFallbackSurface(){const c=document.createElement("canvas");c.width=2048;c.height=1024;const x=c.getContext("2d"),g=x.createLinearGradient(0,0,0,c.height);[[0,"#173976"],[.18,"#2556a3"],[.37,"#3678c7"],[.52,"#2f70c4"],[.70,"#2456a4"],[1,"#102d68"]].forEach(([p,col])=>g.addColorStop(p,col));x.fillStyle=g;x.fillRect(0,0,c.width,c.height);for(let i=0;i<90;i++){const yy=(i*67)%c.height;x.globalAlpha=.07+(i%5)*.012;x.fillStyle=i%3?"#9ac9ec":"#09285f";x.fillRect(0,yy,c.width,1+(i%3));}x.globalAlpha=.55;x.fillStyle="#0a2252";x.beginPath();x.ellipse(c.width*.63,c.height*.61,150,65,-.12,0,Math.PI*2);x.fill();x.globalAlpha=.7;x.strokeStyle="#d9f4ff";x.lineWidth=17;x.beginPath();x.moveTo(c.width*.54,c.height*.55);x.bezierCurveTo(c.width*.58,c.height*.51,c.width*.66,c.height*.52,c.width*.70,c.height*.55);x.stroke();x.globalAlpha=1;return c;}
  createTexture(THREE,image,{srgb=true,repeat=true,anisotropy=10}={}){const t=new THREE.Texture(image);t.colorSpace=srgb?THREE.SRGBColorSpace:THREE.NoColorSpace;t.wrapS=repeat?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping;t.wrapT=THREE.ClampToEdgeWrapping;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;t.anisotropy=Math.min(anisotropy,this.renderer.capabilities.getMaxAnisotropy());t.needsUpdate=true;return t;}
  createThreeScene(THREE){
    this.THREE=THREE;const canvas=document.createElement("canvas"),context=canvas.getContext("webgl2",{alpha:true,antialias:true,powerPreference:"high-performance"});if(!context)throw new Error("WebGL2 unavailable");
    this.renderer=new THREE.WebGLRenderer({canvas,context,alpha:true,antialias:true});this.renderer.setClearColor(0x010611,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.viewport.replaceChildren(canvas);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(34,1,.1,320);this.camera.position.set(0,0,7);
    this.neptuneTexture=this.createTexture(THREE,this.surface,{anisotropy:12});const bump=this.bumpSurface?this.createTexture(THREE,this.bumpSurface,{srgb:false,anisotropy:8}):null;const clouds=this.cloudSurface?this.createTexture(THREE,this.cloudSurface,{anisotropy:10}):null;
    this.neptuneMaterial=new THREE.MeshStandardMaterial({map:this.neptuneTexture,bumpMap:bump,bumpScale:.006,roughness:.91,metalness:0,color:0xeaf5ff});
    this.systemGroup=new THREE.Group();this.systemGroup.rotation.y=this.viewYaw;this.scene.add(this.systemGroup);this.axialGroup=new THREE.Group();this.axialGroup.rotation.z=THREE.MathUtils.degToRad(NEPTUNE_TILT_DEG);this.systemGroup.add(this.axialGroup);
    this.planet=new THREE.Mesh(new THREE.SphereGeometry(1,176,120),this.neptuneMaterial);this.planet.scale.y=.983;this.planet.rotation.y=this.renderedRotation;this.axialGroup.add(this.planet);
    const cloudMat=new THREE.MeshStandardMaterial({map:clouds||this.neptuneTexture,transparent:true,opacity:clouds?.18:.08,depthWrite:false,roughness:.96,metalness:0,color:0xe9f9ff,alphaTest:clouds?.01:0});this.cloudLayer=new THREE.Mesh(new THREE.SphereGeometry(1.009,144,96),cloudMat);this.cloudLayer.scale.y=.983;this.axialGroup.add(this.cloudLayer);
    const cloud2Mat=cloudMat.clone();cloud2Mat.opacity=clouds?.075:.035;cloud2Mat.color.set(0xaedfff);this.highCloudLayer=new THREE.Mesh(new THREE.SphereGeometry(1.016,112,80),cloud2Mat);this.highCloudLayer.scale.y=.983;this.axialGroup.add(this.highCloudLayer);
    const atmMat=new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:`varying vec3 vN;varying vec3 vW;void main(){vN=normalize(mat3(modelMatrix)*normal);vec4 w=modelMatrix*vec4(position,1.);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`precision highp float;varying vec3 vN;varying vec3 vW;void main(){vec3 V=normalize(cameraPosition-vW);float rim=pow(1.-max(dot(normalize(vN),V),0.),3.05);vec3 c=mix(vec3(.10,.31,.78),vec3(.35,.78,.98),rim);gl_FragColor=vec4(c*rim*.33,rim*.22);}`});this.atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.038,120,84),atmMat);this.atmosphere.scale.y=.983;this.axialGroup.add(this.atmosphere);
    this.ringGroup=this.createRingSystem(THREE);this.axialGroup.add(this.ringGroup);this.createSemanticObjects(THREE);this.createUranusFallback(THREE);this.createStars(THREE);
    this.hemi=new THREE.HemisphereLight(0x9ddaff,0x071020,1.03);this.scene.add(this.hemi);this.key=new THREE.DirectionalLight(0xdcefff,2.68);this.key.position.set(-4.7,3.0,5.8);this.scene.add(this.key);this.fill=new THREE.DirectionalLight(0x3e78cc,.64);this.fill.position.set(4.5,-1.0,3.0);this.scene.add(this.fill);
    canvas.addEventListener("webglcontextlost",e=>{e.preventDefault();this.createCanvasFallback();this.resize();if(this.active)this.render();},{once:true});this.mode="webgl";this.element.dataset.renderer="webgl";
  }
  createRingSystem(THREE){const g=new THREE.Group(),specs=[[1.34,1.355,.075,0x39424e],[1.49,1.505,.095,0x4c5664],[1.58,1.61,.06,0x343e4c],[1.71,1.725,.075,0x4e5968],[1.91,1.928,.12,0x5f6872]];for(const [a,b,o,c] of specs){const m=new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,depthTest:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.NormalBlending});m.userData.baseOpacity=o;const ring=new THREE.Mesh(new THREE.RingGeometry(a,b,320,2),m);ring.rotation.x=Math.PI/2;ring.renderOrder=1;g.add(ring);}const arcMat=new THREE.MeshBasicMaterial({color:0x737a84,transparent:true,opacity:.12,depthTest:true,depthWrite:false,side:THREE.DoubleSide});arcMat.userData.baseOpacity=.12;for(const [start,len,op] of [[.18,.20,.13],[.43,.13,.10],[.63,.19,.11],[.88,.10,.08]]){const m=arcMat.clone();m.opacity=op;m.userData.baseOpacity=op;const arc=new THREE.Mesh(new THREE.RingGeometry(1.918,1.945,72,1,start*Math.PI*2,len*Math.PI*2),m);arc.rotation.x=Math.PI/2;arc.renderOrder=1;g.add(arc);}return g;}
  createSemanticObjects(THREE){
    this.magnetosphereGroup=new THREE.Group();const magMat=new THREE.LineBasicMaterial({color:0xa98add,transparent:true,opacity:.32,depthWrite:false});for(const s of [1,1.28,1.58]){const pts=[];for(let i=0;i<128;i++){const a=i/128*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*2.05*s,Math.sin(a)*.68*s,0));}const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(pts),magMat.clone());line.rotation.z=THREE.MathUtils.degToRad(47);line.position.x=.36;this.magnetosphereGroup.add(line);}this.magnetosphereGroup.visible=false;this.systemGroup.add(this.magnetosphereGroup);
    this.tritonGroup=new THREE.Group();const tm=new THREE.MeshStandardMaterial({color:0xe2d9d0,roughness:1,metalness:0});if(this.tritonSurface){const tt=this.createTexture(THREE,this.tritonSurface,{anisotropy:8});tm.map=tt;}this.triton=new THREE.Mesh(new THREE.SphereGeometry(.18,64,44),tm);this.triton.position.set(-2.35,.48,.1);this.tritonGroup.add(this.triton);const orbitPts=[];for(let i=0;i<160;i++){const a=i/160*Math.PI*2;orbitPts.push(new THREE.Vector3(Math.cos(a)*2.4,Math.sin(a)*.66,0));}this.tritonOrbit=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(orbitPts),new THREE.LineBasicMaterial({color:0xaab8c9,transparent:true,opacity:.23,depthWrite:false}));this.tritonOrbit.rotation.z=-.18;this.tritonGroup.add(this.tritonOrbit);this.tritonGroup.visible=false;this.systemGroup.add(this.tritonGroup);
    const anchor=new THREE.Object3D(),lat=-22*Math.PI/180,lon=133.2*Math.PI/180,r=1.026;anchor.position.set(r*Math.cos(lat)*Math.sin(lon),r*Math.sin(lat),r*Math.cos(lat)*Math.cos(lon));this.stormAnchor=anchor;this.planet.add(anchor);
  }
  createUranusFallback(THREE){const m=new THREE.MeshStandardMaterial({color:0xb5dfdf,roughness:.94,metalness:0});if(this.uranusSurface){const t=this.createTexture(THREE,this.uranusSurface,{anisotropy:10});m.map=t;}this.legacyUranusPlanet=new THREE.Mesh(new THREE.SphereGeometry(1,112,72),m);this.legacyUranusPlanet.scale.y=.974;this.legacyUranusGroup=new THREE.Group();this.legacyUranusGroup.rotation.z=THREE.MathUtils.degToRad(97.77);this.legacyUranusGroup.add(this.legacyUranusPlanet);const rings=new THREE.Group();for(const k of [1.35,1.52,1.72,1.92]){const rm=new THREE.MeshBasicMaterial({color:0x48565a,transparent:true,opacity:.20,depthTest:true,depthWrite:false,side:THREE.DoubleSide});const rr=new THREE.Mesh(new THREE.RingGeometry(k,k+.018,192,2),rm);rr.rotation.x=Math.PI/2;rings.add(rr);}this.legacyUranusGroup.add(rings);this.scene.add(this.legacyUranusGroup);this.legacyUranusGroup.visible=false;this.travelUranusGroup=this.legacyUranusGroup;this.travelUranus=this.legacyUranusPlanet;}
  createStars(THREE){const count=this.mobile?360:760,positions=new Float32Array(count*3);for(let i=0;i<count;i++){const a=i*12.9898;positions[i*3]=(Math.sin(a)*.5)*36;positions[i*3+1]=(Math.sin(a*1.71+.3)*.5)*21;positions[i*3+2]=-4-Math.abs(Math.sin(a*2.11))*48;}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(positions,3));this.stars=new THREE.Points(g,new THREE.PointsMaterial({color:0xb5cbe7,size:.024,transparent:true,opacity:.48,sizeAttenuation:true}));this.scene.add(this.stars);}
  createCanvasFallback(){this.renderer?.dispose?.();this.renderer=null;const c=document.createElement("canvas");this.canvas=c;this.ctx=c.getContext("2d");this.viewport.replaceChildren(c);this.mode="canvas";this.element.dataset.renderer="canvas";}
  resize(){const r=this.viewport.getBoundingClientRect();this.width=Math.max(1,Math.floor(r.width));this.height=Math.max(1,Math.floor(r.height));const wasMobile=this.mobile;this.mobile=this.width<=700||this.height>this.width*1.18;const dpr=Math.min(devicePixelRatio||1,this.mobile?1.45:2);if(this.mode==="webgl"&&this.renderer){this.renderer.setPixelRatio(dpr);this.renderer.setSize(this.width,this.height,false);this.camera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();}else if(this.canvas){this.canvas.width=Math.max(1,Math.floor(this.width*dpr));this.canvas.height=Math.max(1,Math.floor(this.height*dpr));this.canvas.style.width=this.width+"px";this.canvas.style.height=this.height+"px";this.ctx.setTransform(dpr,0,0,dpr,0,0);}if(wasMobile!==this.mobile&&!this.travelMode&&!this.exploring){this.viewCameraZ=this.mobile?7.7:7.0;this.focusFrom.z=this.viewCameraZ;this.focusTo.z=this.viewCameraZ;}if(this.active)this.render();}
  bindUranusVisualSource(owner){this._uranusVisualOwner=owner||null;return Boolean(this._uranusVisualOwner);}
  _borrowUranus({uranusRotation,uranusTime}={}){const o=this._uranusVisualOwner;if(!o||this.mode!=="webgl"||o.mode!=="webgl"||!this.scene||!o.systemGroup)return false;cancelAnimationFrame(o.frame);o.frame=null;this.scene.add(o.systemGroup);this.travelUranusGroup=o.systemGroup;this.travelUranus=o.planet;this._borrowedUranus=true;this._uranusStartRotation=Number.isFinite(uranusRotation)?uranusRotation:(o.planet?.rotation?.y??2.15);this._uranusTimeStart=Number.isFinite(uranusTime)?uranusTime:(o.time??8.5);this.travelUranus.rotation.y=this._uranusStartRotation;this.legacyUranusGroup.visible=false;return true;}
  _releaseUranus(){if(!this._borrowedUranus)return;const o=this._uranusVisualOwner;this._uranusEndRotation=this.travelUranus?.rotation.y??this._uranusStartRotation;this._uranusEndTime=this._uranusVisualTime??this._uranusTimeStart;if(o?.scene&&o?.systemGroup){o.scene.add(o.systemGroup);o.time=this._uranusEndTime;o.rotationBase=this._uranusEndRotation-o.time*.021;o.renderedRotation=this._uranusEndRotation;o.planet.rotation.y=this._uranusEndRotation;}this.travelUranusGroup=this.legacyUranusGroup;this.travelUranus=this.legacyUranusPlanet;this._borrowedUranus=false;}
  getUranusVisualRotation(){return Number.isFinite(this._uranusEndRotation)?this._uranusEndRotation:(this._uranusVisualOwner?.planet?.rotation?.y??2.15);} getUranusVisualTime(){return Number.isFinite(this._uranusEndTime)?this._uranusEndTime:(this._uranusVisualOwner?.time??8.5);}
  start({settled=false,rotation=null,time=null}={}){this.active=true;this.travelMode=null;this.travelCallbacks={};this.time=Number.isFinite(time)?time:(settled?8.5:0);this.rotationBase=Number.isFinite(rotation)?rotation-this.time*.026:-1.90;this.renderedRotation=this.rotationBase+this.time*.026;this.exploring=false;this.explorationBlend=this.explorationBlendTarget=0;this.element.hidden=false;this.element.style.opacity="1";this.element.classList.remove("is-exploring","is-leaving");this.caption.classList.remove("is-visible");this.caption.inert=true;this.exploration.inert=true;this.viewYaw=-.42;this.viewCameraZ=this.mobile?7.7:7.0;this.setExplorationStop(0,{immediate:true,announce:false});this.prepare();this.resize();cancelAnimationFrame(this.frame);this.previous=performance.now();this.tick(this.previous);}
  stop(){this.active=false;this.travelMode=null;this.travelCallbacks={};cancelAnimationFrame(this.frame);this.frame=null;this.element.hidden=true;this.element.style.opacity="0";this.element.classList.remove("is-exploring","is-leaving");this.exploring=false;this.caption.inert=true;this.exploration.inert=true;this.contextMedia.replaceChildren();this.contextMedia.hidden=true;this._releaseUranus();}
  enterExploration(){if(!this.active||this.exploring||this.travelMode)return;this.exploring=true;this.explorationBlendTarget=1;this.element.classList.add("is-exploring");this.caption.inert=true;this.exploration.inert=false;this._applyTopicView(this.topicIndex,false);if(!this.frame){this.previous=performance.now();this.tick(this.previous);}document.getElementById("announcement").textContent=`Mode eksplorasi Neptunus dimulai. ${NEPTUNE_EXPLORATION_STOPS[this.topicIndex].title}.`;requestAnimationFrame(()=>this.topicTitle.focus({preventScroll:true}));}
  exitExploration(){if(!this.exploring)return;this.exploring=false;this.explorationBlendTarget=0;this.element.classList.remove("is-exploring");this.exploration.inert=true;this.caption.inert=false;this._beginFocus(-.42,this.mobile?7.7:7.0);this._setSemantic("identity");if(!this.frame){this.previous=performance.now();this.tick(this.previous);}document.getElementById("announcement").textContent="Kembali ke panorama Neptunus.";requestAnimationFrame(()=>this.exploreButton.focus({preventScroll:true}));}
  setExplorationStop(index,{immediate=false,announce=true}={}){const prev=this.topicIndex??0,next=Math.max(0,Math.min(NEPTUNE_EXPLORATION_STOPS.length-1,index)),stop=NEPTUNE_EXPLORATION_STOPS[next];this.topicIndex=next;if(!immediate){this.exploration.classList.remove("is-switching-next","is-switching-prev");void this.exploration.offsetWidth;this.exploration.classList.add(next>=prev?"is-switching-next":"is-switching-prev");clearTimeout(this._switchTimer);this._switchTimer=setTimeout(()=>this.exploration.classList.remove("is-switching-next","is-switching-prev"),560);}this.topicKicker.textContent=stop.kicker;this.topicTitle.textContent=stop.title;this.topicSubtitle.textContent=stop.subtitle;this.topicSummary.textContent=stop.summary;this.topicFacts.replaceChildren(...stop.facts.map(f=>{const li=document.createElement("li");li.textContent=f;return li;}));this.topicSource.href=stop.source;this.topicCurrent.textContent=String(next+1).padStart(2,"0");this.topicPrev.disabled=next===0;this.topicNext.disabled=next===NEPTUNE_EXPLORATION_STOPS.length-1;Array.from(this.topicProgress.children).forEach((bar,i)=>bar.classList.toggle("is-active",i===next));window.ExplorationMedia?.render?.("neptune",stop,this.contextMedia);this._applyTopicView(next,immediate||!this.exploring);if(this.active&&!this.frame){this.previous=performance.now();this.tick(this.previous);}if(announce&&this.exploring)document.getElementById("announcement").textContent=`Eksplorasi Neptunus ${next+1} dari ${NEPTUNE_EXPLORATION_STOPS.length}: ${stop.title}.`;}
  _applyTopicView(index,immediate=false){const stop=NEPTUNE_EXPLORATION_STOPS[index],views=[[-.42,7.0],[-.30,7.35],[-.55,6.75],[-.08,6.6],[-.68,6.25],[-.72,6.45],[.28,7.7],[-.20,7.65],[.16,7.65],[-.47,7.2],[-.42,7.1]],v=views[index]||views[0];this._setSemantic(stop.semantic);if(immediate){this.viewYaw=v[0];this.viewCameraZ=this.mobile?v[1]+.68:v[1];this.focusState="FOCUSED_IDLE";this.focusProgress=1;}else this._beginFocus(v[0],this.mobile?v[1]+.68:v[1]);}
  _beginFocus(yaw,z){this.focusFrom={yaw:this.viewYaw,z:this.viewCameraZ};this.focusTo={yaw,z};this.focusProgress=0;this.focusState="FOCUS_TRANSITION";}
  _setSemantic(kind){this.semantic=kind;this.ringAnnotation.hidden=kind!=="rings";this.windOverlay.hidden=!(kind==="winds"||kind==="clouds");this.endBadge.hidden=kind!=="final";if(this.stormAnnotation)this.stormAnnotation.hidden=kind!=="storm";if(this.magnetosphereGroup)this.magnetosphereGroup.visible=kind==="magnetosphere";if(this.tritonGroup)this.tritonGroup.visible=kind==="triton";}
  _updateFocus(delta){if(this.focusState!=="FOCUS_TRANSITION")return;this.focusProgress=Math.min(1,this.focusProgress+delta/(this.motion.matches?.05:.95));const t=this.travelSmooth(this.focusProgress);this.viewYaw=this.focusFrom.yaw+(this.focusTo.yaw-this.focusFrom.yaw)*t;this.viewCameraZ=this.focusFrom.z+(this.focusTo.z-this.focusFrom.z)*t;if(this.focusProgress>=1)this.focusState="FOCUSED_IDLE";}
  beginTravelFromUranus({onCovered,onComplete,uranusRotation=2.15,uranusTime=8.5,direction=1}={}){if(this.active&&this.travelMode)return;this.active=true;this.exploring=false;this.travelMode="from-uranus";this.travelDirection=direction>=0?1:-1;this.travelCallbacks={onCovered,onComplete};this.travelStartedAt=0;this.time=0;this.travelDuration=this.motion.matches?.55:8.3;this.travelCoveredFired=false;this.travelCompleteFired=false;this.element.hidden=false;this.element.style.opacity="1";this.element.classList.add("is-leaving");this.caption.classList.remove("is-visible");this.caption.inert=true;this.exploration.inert=true;if(this.mode==="pending"){this.surface=this.surface||this.makeFallbackSurface();this.createCanvasFallback();}this.prepare();this.resize();this._borrowUranus({uranusRotation,uranusTime});if(this.travelUranus)this.travelUranus.rotation.y=uranusRotation;cancelAnimationFrame(this.frame);this.previous=performance.now();this.tick(this.previous);}
  beginTravelToUranus({onCovered,onComplete,direction=-1}={}){if(!this.active||this.travelMode||this.exploring)return;this._borrowUranus({uranusRotation:this._uranusVisualOwner?.planet?.rotation?.y,uranusTime:this._uranusVisualOwner?.time});this.travelMode="to-uranus";this.travelDirection=direction>=0?1:-1;this.travelCallbacks={onCovered,onComplete};this.travelStartedAt=this.time;this.travelDuration=this.motion.matches?.55:8.3;this.travelCoveredFired=false;this.travelCompleteFired=false;this.element.classList.add("is-leaving");this.caption.inert=true;if(!this.frame){this.previous=performance.now();this.tick(this.previous);}}
  tick(now){this.frame=null;if(!this.active||document.hidden)return;const d=Math.min((now-this.previous)/1000,.12);this.previous=now;this.time+=d;const damp=1-Math.exp(-d*2);this.cameraOffset.x+=(this.pointer.x-this.cameraOffset.x)*damp;this.cameraOffset.y+=(this.pointer.y-this.cameraOffset.y)*damp;const ed=this.motion.matches?1:1-Math.exp(-d*3);this.explorationBlend+=(this.explorationBlendTarget-this.explorationBlend)*ed;this._updateFocus(d);this.render();if(this.active&&!this.motion.matches)this.frame=requestAnimationFrame(t=>this.tick(t));else if(this.active&&(this.travelMode||this.focusState==="FOCUS_TRANSITION"||Math.abs(this.explorationBlend-this.explorationBlendTarget)>.002))this.frame=requestAnimationFrame(t=>this.tick(t));}
  render(){if(this.travelMode)this.renderTravel();else this.renderNeptune();}
  renderNeptune(){const blend=this.explorationBlend,x=this.mobile?0:(.74+blend*.07),y=this.mobile?(-.03-blend*.07):(.015+blend*.015),scale=this.mobile?.83:1.035,rotationSpeed=this.semantic==="storm"&&this.exploring?.008:.026;this.renderedRotation=this.rotationBase+this.time*rotationSpeed;if(this.mode==="webgl"){this.systemGroup.visible=true;this.travelUranusGroup.visible=false;this.systemGroup.position.set(x,y,0);this.systemGroup.scale.setScalar(scale);this.systemGroup.rotation.y=this.viewYaw;this.planet.rotation.y=this.renderedRotation;this.cloudLayer.rotation.y=this.renderedRotation+this.time*.0062;this.highCloudLayer.rotation.y=this.renderedRotation-this.time*.0037;const ringPulse=1+.018*Math.sin(this.time*.11);this.ringGroup.children.forEach(r=>r.material.opacity=r.material.userData.baseOpacity*ringPulse);if(this.tritonGroup.visible){const a=-this.time*.11;this.triton.position.set(Math.cos(a)*2.35,.48+Math.sin(a*.7)*.12,Math.sin(a)*.30);this.triton.rotation.y+=.003;}this.camera.position.set(this.motion.matches?0:this.cameraOffset.x*.08,this.motion.matches?0:-this.cameraOffset.y*.055,this.viewCameraZ);this.camera.lookAt(0,0,0);this.renderer.render(this.scene,this.camera);this._updateStormAnnotation();}else this.drawCanvasNeptune(x,y,scale);if(this.time>1&&!this.travelMode){this.caption.classList.add("is-visible");this.caption.inert=this.exploring;this.credit.style.opacity=this.exploring?"0":".86";}}
  _updateStormAnnotation(){if(!this.stormAnnotation||this.stormAnnotation.hidden||!this.stormAnchor||!this.camera||!this.THREE)return;const p=new this.THREE.Vector3();this.stormAnchor.getWorldPosition(p);p.project(this.camera);const visible=p.z<1&&p.z>-1&&Math.abs(p.x)<1.15&&Math.abs(p.y)<1.15;this.stormAnnotation.style.opacity=visible?"1":"0";if(visible){this.stormAnnotation.style.left=`${(p.x*.5+.5)*100}%`;this.stormAnnotation.style.top=`${(-p.y*.5+.5)*100}%`;}}
  renderTravel(){const s=this.travelState(),reverse=this.travelMode==="to-uranus",raw=this.clamp((this.time-this.travelStartedAt)/this.travelDuration),direction=this.travelDirection>=0?1:-1,aspect=this.camera?.aspect||this.width/this.height,half=Math.tan((34*Math.PI/180)/2)*7,separationMagnitude=half*aspect*(this.mobile?4.05:3.35),separation=separationMagnitude*direction,cameraX=separation*s.pan,cameraZ=7*(1+1.5*s.pullback*(1-s.approach)),neptuneLane=reverse?0:separation,uranusLane=reverse?separation:0;const nX=this.mobile?0:.74,nY=this.mobile?-.03:.015,nScale=this.mobile?.83:1.035,uX=this.mobile?0:.72,uY=this.mobile?-.03:.02,uScale=this.mobile?.82:1.02;
    if(this.mode==="webgl"){this.systemGroup.visible=true;this.travelUranusGroup.visible=true;this.systemGroup.position.set(neptuneLane+nX,nY,0);this.systemGroup.scale.setScalar(nScale);this.systemGroup.rotation.y=-.42;this.planet.rotation.y=this.rotationBase+this.time*.026;this.cloudLayer.rotation.y=this.planet.rotation.y+this.time*.0062;this.highCloudLayer.rotation.y=this.planet.rotation.y-this.time*.0037;const farFactor=this.clamp((cameraZ-7)/10.5);this.ringGroup.children.forEach(r=>r.material.opacity=r.material.userData.baseOpacity*(1.12+.48*farFactor));
      this.travelUranusGroup.position.set(uranusLane+uX,uY,0);this.travelUranusGroup.scale.setScalar(uScale);const elapsed=Math.max(0,this.time-this.travelStartedAt),visualTime=this._uranusTimeStart+elapsed,rotation=this._uranusStartRotation+elapsed*.021;this._uranusVisualTime=visualTime;this.travelUranus.rotation.y=rotation;const o=this._uranusVisualOwner;if(o?.cloudLayer)o.cloudLayer.rotation.y=rotation+visualTime*.003;if(o?.ringGroup){const pulse=1+.025*Math.sin(visualTime*.13);o.ringGroup.children.forEach(r=>r.material.opacity=r.material.userData.baseOpacity*pulse);}
      if(this.stars)this.stars.position.x=cameraX*.94;this.camera.position.set(cameraX,0,cameraZ);const lookOffset=Math.sin(s.pan*Math.PI)*separationMagnitude*.055*direction;this.camera.lookAt(cameraX+lookOffset,0,0);this.renderer.render(this.scene,this.camera);
    }else this.drawCanvasTravel(s,reverse,direction);
    if(!this.travelCoveredFired&&raw>=.11){this.travelCoveredFired=true;this.travelCallbacks.onCovered?.();}
    if(raw>=.999&&!this.travelCompleteFired){this.travelCompleteFired=true;const cb=this.travelCallbacks.onComplete;this._releaseUranus();if(!reverse){this.travelMode=null;this.travelCallbacks={};this.element.classList.remove("is-leaving");this.caption.classList.add("is-visible");this.caption.inert=false;this.credit.style.opacity=".86";document.getElementById("announcement").textContent="Tiba di Neptunus.";}cb?.();}
  }
  drawCanvasStars(c,offset){c.fillStyle="#afc9e8";for(let i=0;i<150;i++){const xx=((i*137.5+offset*31)%this.width+this.width)%this.width,yy=(i*83.7)%this.height;c.globalAlpha=.16+(i%5)*.07;c.fillRect(xx,yy,1,1);}c.globalAlpha=1;}
  drawCanvasNeptune(x,y,scale,{clear=true}={}){const c=this.ctx;if(!c)return;if(clear){c.clearRect(0,0,this.width,this.height);this.drawCanvasStars(c,0);}const cx=this.width*(.5+x*.09),cy=this.height*(.48-y*.06),r=Math.min(this.width,this.height)*(this.mobile?.18:.205)*scale;c.save();c.translate(cx,cy);c.rotate(.18);c.strokeStyle="rgba(72,78,91,.33)";c.lineWidth=Math.max(1,r*.012);for(const k of [1.34,1.49,1.60,1.72,1.92]){c.beginPath();c.ellipse(0,0,r*k,r*k*.23,0,Math.PI,Math.PI*2);c.stroke();}c.restore();c.save();c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.clip();c.drawImage(this.surface,0,0,this.surface.width,this.surface.height,cx-r,cy-r,r*2,r*2);const sh=c.createRadialGradient(cx-r*.35,cy-r*.32,r*.1,cx,cy,r*1.05);sh.addColorStop(0,"rgba(175,225,255,.10)");sh.addColorStop(.70,"rgba(41,102,185,.05)");sh.addColorStop(1,"rgba(2,8,28,.44)");c.fillStyle=sh;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.restore();c.save();c.translate(cx,cy);c.rotate(.18);c.strokeStyle="rgba(87,92,104,.44)";for(const k of [1.34,1.49,1.60,1.72,1.92]){c.beginPath();c.ellipse(0,0,r*k,r*k*.23,0,0,Math.PI);c.stroke();}c.restore();}
  drawCanvasTravel(s,reverse,direction){const c=this.ctx;if(!c)return;c.clearRect(0,0,this.width,this.height);const shift=this.width*.34*s.pan*direction;this.drawCanvasStars(c,-shift*.15);const nAlpha=reverse?1-s.progress:s.progress,uAlpha=reverse?s.progress:1-s.progress;c.save();c.globalAlpha=Math.max(.12,nAlpha);c.translate(reverse?-shift:shift,0);this.drawCanvasNeptune(0,0,.55+.45*nAlpha,{clear:false});c.restore();c.globalAlpha=Math.max(.12,uAlpha);const cx=this.width*.5+(reverse?shift:-shift),cy=this.height*.48,r=Math.min(this.width,this.height)*(.15+.06*uAlpha);c.fillStyle="#9fcfd0";c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.save();c.translate(cx,cy);c.rotate(-.28);c.strokeStyle="rgba(75,88,91,.50)";c.lineWidth=1.4;for(const k of [1.35,1.55,1.78]){c.beginPath();c.ellipse(0,0,r*k,r*k*.25,0,0,Math.PI*2);c.stroke();}c.restore();c.globalAlpha=1;}
};
