"use strict";

const URANUS_TEXTURE = "assets/textures/uranus-atmosphere-4k.jpg";
const URANUS_BUMP = "assets/textures/uranus-cloud-bump-2k.jpg";
const URANUS_SATURN_TEXTURE = "assets/textures/saturn-atmosphere-4k.jpg";
const URANUS_TILT_DEG = 97.77;

const URANUS_EXPLORATION_STOPS = Object.freeze([
  {
    kicker:"IDENTITAS URANUS", title:"Raksasa Es yang Menyamping", subtitle:"Planet ketujuh dengan warna biru-hijau dan orientasi paling ganjil",
    summary:"Uranus adalah planet ketujuh dari Matahari dan salah satu dari dua raksasa es. Warna biru-hijaunya berasal dari metana di atmosfer, sementara orientasi sumbunya membuat planet ini tampak berputar hampir menyamping.",
    facts:["Diameter ekuator Uranus sekitar 51.118 km.","Jarak rata-ratanya dari Matahari sekitar 19 AU atau 2,9 miliar km.","Satu hari Uranus berlangsung sekitar 17 jam dan satu tahunnya sekitar 84 tahun Bumi."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"identity",
    images:[{src:"https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/2023/09/p/i/a/1/PIA18182-1.jpg?crop=faces%2Cfocalpoint&fit=clip&h=1720&w=1720",alt:"Citra global Uranus dari Voyager 2",credit:"NASA/JPL",source:"https://science.nasa.gov/uranus/facts/",caption:"Uranus · raksasa es yang hampir berputar menyamping",fit:"contain",type:"CITRA WAHANA"}]
  },
  {
    kicker:"KEMIRINGAN 97.77 DERAJAT", title:"Dunia yang Hampir Menggelinding", subtitle:"Sumbu rotasi hampir sejajar dengan bidang orbit",
    summary:"Kemiringan sumbu Uranus mencapai sekitar 97,77 derajat. Planet ini seolah berputar sambil berbaring, berbeda sangat jauh dari orientasi Jupiter dan Saturnus.",
    facts:["Kemiringan 97,77 derajat adalah salah satu ciri paling khas Uranus.","Cincin dan orbit bulan-bulan utama mengikuti ekuator Uranus yang sangat miring.","Orientasi ekstrem ini kemungkinan berkaitan dengan sejarah pembentukan Uranus yang sangat dinamis."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"axis",
    images:[{src:"./assets/uranus-tilt-diagram.svg",alt:"Diagram kemiringan sumbu Uranus 97,77 derajat",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/uranus/facts/",caption:"Sumbu rotasi Uranus miring 97,77°",fit:"contain"}]
  },
  {
    kicker:"MUSIM EKSTREM", title:"Puluhan Tahun Cahaya dan Gelap", subtitle:"Kemiringan ekstrem menciptakan musim yang sangat panjang",
    summary:"Karena Uranus hampir berputar menyamping, setiap kutub dapat lama menghadap Matahari. Selama sebagian orbitnya, satu belahan menerima cahaya terus-menerus sementara belahan lain mengalami musim dingin gelap yang panjang.",
    facts:["Satu tahun Uranus berlangsung sekitar 84 tahun Bumi.","Setiap kutub dapat mengalami periode panjang ketika Matahari berada hampir tepat di atasnya.","Belahan yang berlawanan dapat mengalami sekitar 21 tahun kegelapan musim dingin."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"seasons",
    images:[{src:"./assets/uranus-seasons-diagram.svg",alt:"Diagram musim ekstrem Uranus akibat kemiringan sumbu",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/uranus/facts/",caption:"Kemiringan Uranus membentuk musim yang berlangsung puluhan tahun",fit:"contain"}]
  },
  {
    kicker:"ATMOSFER METANA", title:"Mengapa Uranus Berwarna Cyan", subtitle:"Metana menyerap cahaya merah dan memperkuat kesan biru-hijau",
    summary:"Atmosfer Uranus didominasi hidrogen dan helium dengan sejumlah metana. Metana menyerap bagian merah dari cahaya, sehingga cahaya yang dipantulkan kembali memberi Uranus warna biru-hijau yang lembut.",
    facts:["Atmosfer mengandung hidrogen, helium, metana, serta jejak air dan amonia.","Metana memengaruhi warna, bukan berarti Uranus dipenuhi awan hijau terang.","Pengamatan modern menunjukkan awan dan fitur terang yang dapat berubah seiring musim."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"atmosphere",
    images:[{src:"./assets/uranus-methane-diagram.svg",alt:"Diagram bagaimana metana memengaruhi warna Uranus",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/uranus/facts/",caption:"Metana menyerap merah dan meninggalkan kesan biru-hijau",fit:"contain"}]
  },
  {
    kicker:"STRUKTUR RAKSASA ES", title:"Bukan Bola Es Padat", subtitle:"Fluida panas dan padat mengelilingi inti kecil",
    summary:"Istilah raksasa es tidak berarti Uranus adalah bola es beku. Sebagian besar massanya diperkirakan berupa fluida panas dan padat yang kaya air, metana, dan amonia di atas inti batuan yang relatif kecil.",
    facts:["Lebih dari 80 persen massa Uranus diperkirakan berupa material raksasa es di interiornya.","Uranus tidak memiliki permukaan padat tempat wahana dapat mendarat.","Tekanan dan suhu meningkat ekstrem menuju bagian dalam planet."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"interior",
    images:[{src:"./assets/uranus-interior-diagram.svg",alt:"Diagram konseptual struktur interior Uranus",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/uranus/facts/",caption:"Lapisan konseptual interior Uranus",fit:"contain"}]
  },
  {
    kicker:"CINCIN URANUS", title:"Cincin Gelap yang Nyaris Tersembunyi", subtitle:"Tiga belas cincin redup mengelilingi ekuator Uranus",
    summary:"Uranus mempunyai sistem cincin yang jauh lebih gelap dan sempit daripada Saturnus. Cincin-cincin ini mengikuti ekuator planet, sehingga seluruh sistem cincin ikut tampak sangat miring bersama Uranus.",
    facts:["NASA mencatat 13 cincin Uranus.","Sembilan cincin bagian dalam umumnya sempit dan berwarna abu-abu gelap.","Cincin luar mengandung material debu dan tetap jauh lebih redup daripada cincin Saturnus."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"rings",
    images:[{src:"https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia01/pia01977/PIA01977.jpg?crop=faces%2Cfocalpoint&fit=clip&h=735&w=754",alt:"Citra cincin Uranus dari Voyager 2",credit:"NASA/JPL",source:"https://science.nasa.gov/uranus/facts/",caption:"Cincin Uranus · sempit, gelap, dan redup",fit:"contain",type:"CITRA WAHANA"}]
  },
  {
    kicker:"MEDAN MAGNET YANG ANEH", title:"Magnetosfer yang Tidak Sejajar", subtitle:"Sumbu magnet sangat miring dan bergeser dari pusat planet",
    summary:"Medan magnet Uranus tidak sejajar dengan sumbu rotasinya. Sumbu magnetnya miring hampir 60 derajat dan pusat medan magnet juga bergeser dari pusat planet, menghasilkan magnetosfer yang bentuknya sangat tidak biasa.",
    facts:["Sumbu magnet Uranus miring hampir 60 derajat terhadap sumbu rotasi.","Pusat medan magnet bergeser sekitar sepertiga radius planet.","Rotasi menyamping Uranus memelintir magnetotail menjadi struktur panjang seperti pembuka botol."],
    source:"https://science.nasa.gov/uranus/facts/", semantic:"magnetosphere",
    images:[{src:"./assets/uranus-magnetosphere-diagram.svg",alt:"Diagram magnetosfer Uranus yang miring dan tidak terpusat",credit:"Visualisasi ANTARA berdasarkan NASA Science",source:"https://science.nasa.gov/uranus/facts/",caption:"Medan magnet Uranus miring dan off-center",fit:"contain"}]
  },
  {
    kicker:"MIRANDA", title:"Bulan dengan Lanskap Terpecah", subtitle:"Tebing, lembah, coronae, dan sejarah geologi yang rumit",
    summary:"Miranda adalah bulan kecil Uranus dengan permukaan yang sangat beragam. Voyager 2 mengungkap coronae, lembah besar, patahan, dan wilayah dengan usia geologi berbeda yang tampak seperti potongan lanskap yang disatukan.",
    facts:["Miranda berdiameter sekitar 472 km.","Beberapa jurangnya dapat mencapai kedalaman berkali-kali Grand Canyon.","Miranda adalah yang terkecil dan paling dekat di antara lima bulan besar Uranus."],
    source:"https://science.nasa.gov/uranus/moons/miranda/", semantic:"miranda",
    images:[{src:"https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00042/PIA00042.jpg?crop=faces%2Cfocalpoint&fit=clip&h=600&w=459",alt:"Citra Miranda dari Voyager 2",credit:"NASA/JPL",source:"https://science.nasa.gov/uranus/moons/miranda/",caption:"Miranda · dunia es kecil dengan lanskap yang sangat beragam",fit:"contain",type:"CITRA WAHANA"}]
  },
  {
    kicker:"TITANIA & OBERON", title:"Dua Bulan Terbesar", subtitle:"Dunia es-batuan di bagian luar sistem Uranus",
    summary:"Titania dan Oberon adalah dua bulan terbesar Uranus. Keduanya merupakan dunia es dan batu dengan permukaan yang banyak berkawah, tetapi Titania juga menunjukkan sistem patahan dan ngarai yang menandakan sejarah geologi internal.",
    facts:["Titania adalah bulan terbesar Uranus dengan diameter sekitar 1.578 km.","Oberon adalah bulan terbesar kedua dengan diameter sekitar 1.523 km.","Per Agustus 2026, NASA mencatat 29 bulan yang diketahui mengorbit Uranus."],
    source:"https://science.nasa.gov/uranus/moons/facts/", semantic:"moons",
    images:[{src:"https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia01/pia01979/PIA01979.jpg?crop=faces%2Cfocalpoint&fit=clip&h=560&w=784",alt:"Titania dipotret Voyager 2",credit:"NASA/JPL",source:"https://science.nasa.gov/photojournal/titania/",caption:"Titania · Voyager 2 · PIA01979",fit:"contain",type:"CITRA WAHANA"},{src:"https://assets.science.nasa.gov/dynamicimage/assets/science/psd/photojournal/pia/pia00/pia00034/PIA00034.jpg?crop=faces%2Cfocalpoint&fit=clip&h=500&w=500",alt:"Oberon dipotret Voyager 2",credit:"NASA/JPL",source:"https://science.nasa.gov/photojournal/oberon/",caption:"Oberon · Voyager 2 · PIA00034",fit:"contain",type:"CITRA WAHANA"}]
  },
  {
    kicker:"VOYAGER 2", title:"Lima Setengah Jam yang Mengubah Uranus", subtitle:"Satu-satunya kunjungan dekat manusia ke sistem Uranus",
    summary:"Voyager 2 melakukan pendekatan terdekat ke Uranus pada 24 Januari 1986. Flyby singkat itu menghasilkan ribuan gambar dan data tentang atmosfer, cincin, medan magnet, serta bulan-bulan Uranus.",
    facts:["Voyager 2 melintas sekitar 81.500 km dari puncak awan Uranus.","Wahana menemukan 10 bulan baru dan dua cincin baru pada saat itu.","Voyager 2 masih menjadi satu-satunya wahana yang pernah mengunjungi Uranus dari dekat."],
    source:"https://science.nasa.gov/mission/voyager/voyager-2/", semantic:"voyager",
    images:[{src:"./assets/uranus-voyager-diagram.svg",alt:"Diagram Voyager 2 terbang melintasi Uranus",credit:"Visualisasi ANTARA berdasarkan NASA/JPL",source:"https://science.nasa.gov/mission/voyager/voyager-2/",caption:"Voyager 2 · flyby Uranus, 24 Januari 1986",fit:"contain"}]
  },
  {
    kicker:"MASA DEPAN EKSPLORASI", title:"Raksasa Es yang Masih Menyimpan Banyak Pertanyaan", subtitle:"Atmosfer, interior, cincin, magnetosfer, dan bulan-bulan menunggu penyelidikan baru",
    summary:"Hanya satu flyby tidak cukup untuk menjawab semua pertanyaan tentang Uranus. Pengamatan dan misi masa depan dapat mengungkap bagaimana raksasa es terbentuk, bagaimana magnetosfer ganjilnya bekerja, dan bagaimana sistem bulan serta cincinnya berevolusi.",
    facts:["Uranus memberi contoh penting untuk memahami raksasa es, tipe planet yang umum ditemukan di luar Tata Surya.","Pertanyaan besar tersisa tentang interior, panas internal, cuaca, medan magnet, dan evolusi bulan-bulannya.","Voyager 2 hanya memiliki sekitar 5,5 jam untuk studi jarak dekat Uranus, sehingga proses jangka panjang belum pernah dipantau dari orbit."],
    source:"https://science.nasa.gov/uranus/", semantic:"future",
    images:[{src:"./assets/uranus-future-diagram.svg",alt:"Diagram tema masa depan eksplorasi Uranus",credit:"Visualisasi ANTARA",source:"https://science.nasa.gov/uranus/",caption:"Pertanyaan ilmiah besar di sistem Uranus",fit:"contain"}]
  }
]);

window.UranusScene = class UranusScene {
  constructor(){
    this.element=document.getElementById("uranus-scene"); this.viewport=document.getElementById("uranus-viewport"); this.caption=this.element.querySelector(".uranus-caption");
    this.title=document.getElementById("uranus-title"); this.exploreButton=document.getElementById("uranus-explore-button"); this.exploration=document.getElementById("uranus-exploration"); this.explorationClose=document.getElementById("uranus-exploration-close");
    this.topicKicker=document.getElementById("uranus-topic-kicker"); this.topicTitle=document.getElementById("uranus-topic-title"); this.topicSubtitle=document.getElementById("uranus-topic-subtitle"); this.topicSummary=document.getElementById("uranus-topic-summary"); this.topicFacts=document.getElementById("uranus-topic-facts"); this.topicSource=document.getElementById("uranus-topic-source"); this.topicCurrent=document.getElementById("uranus-topic-current"); this.topicTotal=document.getElementById("uranus-topic-total"); this.topicPrev=document.getElementById("uranus-topic-prev"); this.topicNext=document.getElementById("uranus-topic-next"); this.topicProgress=document.getElementById("uranus-topic-progress"); this.contextMedia=document.getElementById("uranus-context-media"); this.credit=this.element.querySelector(".uranus-credit");
    this.axisOverlay=document.getElementById("uranus-axis-overlay"); this.ringAnnotation=document.getElementById("uranus-ring-annotation"); this.seasonOverlay=document.getElementById("uranus-season-overlay");
    this.motion=matchMedia("(prefers-reduced-motion: reduce)"); this.loading=null; this.mode="pending"; this.active=false; this.exploring=false; this.topicIndex=0; this.explorationBlend=0; this.explorationBlendTarget=0; this.frame=null; this.previous=0; this.time=0; this.renderedRotation=2.15; this.rotationBase=2.15;
    this.width=1; this.height=1; this.mobile=false; this.pointer={x:0,y:0}; this.cameraOffset={x:0,y:0}; this.travelMode=null; this.travelDirection=1; this.travelCallbacks={}; this.travelStartedAt=0; this.travelDuration=8.3; this.travelCoveredFired=false; this.travelCompleteFired=false; this.focusState="IDLE_ROTATION"; this.focusProgress=1; this.focusFrom={yaw:-.38,z:7.0}; this.focusTo={yaw:-.38,z:7.0}; this.viewYaw=-.38; this.viewCameraZ=7.0;
    this._saturnVisualOwner=null; this._borrowedSaturn=false; this._saturnStartRotation=2.2; this._saturnTimeStart=8.5; this._saturnEndRotation=null; this._saturnEndTime=null;
    this.topicTotal.textContent=String(URANUS_EXPLORATION_STOPS.length).padStart(2,"0"); this.topicProgress.replaceChildren(...URANUS_EXPLORATION_STOPS.map(()=>document.createElement("span")));
    this.setExplorationStop(0,{immediate:true,announce:false});
    this.exploreButton.addEventListener("click",()=>this.enterExploration()); this.explorationClose.addEventListener("click",()=>this.exitExploration()); this.topicPrev.addEventListener("click",()=>this.setExplorationStop(this.topicIndex-1)); this.topicNext.addEventListener("click",()=>this.setExplorationStop(this.topicIndex+1));
    this.element.addEventListener("pointermove",e=>{if(e.pointerType!=="mouse"||this.motion.matches||this.travelMode)return;const r=this.element.getBoundingClientRect();this.pointer.x=(e.clientX-r.left)/r.width-.5;this.pointer.y=(e.clientY-r.top)/r.height-.5;});
    this.element.addEventListener("pointerleave",()=>{this.pointer.x=this.pointer.y=0;}); addEventListener("resize",()=>{if(this.active||!this.element.hidden)this.resize();}); document.addEventListener("visibilitychange",()=>{if(!document.hidden&&this.active&&!this.frame){this.previous=performance.now();this.tick(this.previous);}});
  }
  clamp(v,a=0,b=1){return Math.min(b,Math.max(a,v));} smooth(a,b,v){const t=this.clamp((v-a)/(b-a));return t*t*(3-2*t);} travelSmooth(v){const t=this.clamp(v);return t*t*t*(t*(t*6-15)+10);} loadImage(src){return new Promise((res,rej)=>{const im=new Image();im.decoding="async";im.onload=async()=>{try{await im.decode?.();}catch(_){}res(im);};im.onerror=()=>rej(new Error(`Unable to load ${src}`));im.src=src;});}
  travelState(){const elapsed=this.time-this.travelStartedAt,progress=this.travelSmooth(elapsed/this.travelDuration),pullback=this.travelSmooth(progress/.31),pan=this.travelSmooth((progress-.23)/.39),approach=this.travelSmooth((progress-.58)/.42);return{elapsed,progress,pullback,pan,approach};}
  prepare(){if(this.loading)return this.loading;this.loading=Promise.allSettled([import("./assets/vendor/three/three.module.min.js"),this.loadImage(URANUS_TEXTURE),this.loadImage(URANUS_BUMP),this.loadImage(URANUS_SATURN_TEXTURE)]).then(async([mod,surface,bump,saturn])=>{this.surface=surface.status==="fulfilled"?surface.value:this.makeFallbackSurface();this.bumpSurface=bump.status==="fulfilled"?bump.value:null;this.saturnSurface=saturn.status==="fulfilled"?saturn.value:null;if(mod.status==="fulfilled"){try{this.createThreeScene(mod.value);}catch(e){console.warn("Uranus WebGL unavailable; using Canvas fallback.",e);this.createCanvasFallback();}}else this.createCanvasFallback();this.resize();if(this.renderer?.compileAsync)await this.renderer.compileAsync(this.scene,this.camera);this.element.dataset.ready="true";if(this.active)this.render();}).catch(e=>{console.error("Uranus preparation failed",e);this.surface=this.surface||this.makeFallbackSurface();this.createCanvasFallback();this.resize();this.element.dataset.ready="fallback";});return this.loading;}
  makeFallbackSurface(){const c=document.createElement("canvas");c.width=2048;c.height=1024;const x=c.getContext("2d"),g=x.createLinearGradient(0,0,0,c.height);[[0,"#72aeb7"],[.18,"#91d3d4"],[.36,"#83c9cd"],[.54,"#a7dcda"],[.72,"#7dbdc5"],[1,"#659eab"]].forEach(([p,col])=>g.addColorStop(p,col));x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.globalAlpha=.12;for(let i=0;i<54;i++){x.fillStyle=i%2?"#d5f2ef":"#3b7785";x.fillRect(0,(i*83)%c.height,c.width,1+(i%2));}x.globalAlpha=1;return c;}
  createThreeScene(THREE){
    this.THREE=THREE;const canvas=document.createElement("canvas"),context=canvas.getContext("webgl2",{alpha:true,antialias:true,powerPreference:"high-performance"});if(!context)throw new Error("WebGL2 unavailable");
    this.renderer=new THREE.WebGLRenderer({canvas,context,alpha:true,antialias:true});this.renderer.setClearColor(0x020711,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.viewport.replaceChildren(canvas);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(34,1,.1,300);this.camera.position.set(0,0,7);
    const tex=new THREE.Texture(this.surface);tex.colorSpace=THREE.SRGBColorSpace;tex.wrapS=THREE.RepeatWrapping;tex.wrapT=THREE.ClampToEdgeWrapping;tex.minFilter=THREE.LinearMipmapLinearFilter;tex.magFilter=THREE.LinearFilter;tex.generateMipmaps=true;tex.anisotropy=Math.min(12,this.renderer.capabilities.getMaxAnisotropy());tex.needsUpdate=true;this.uranusTexture=tex;
    let bump=null;if(this.bumpSurface){bump=new THREE.Texture(this.bumpSurface);bump.colorSpace=THREE.NoColorSpace;bump.wrapS=THREE.RepeatWrapping;bump.minFilter=THREE.LinearMipmapLinearFilter;bump.magFilter=THREE.LinearFilter;bump.generateMipmaps=true;bump.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());bump.needsUpdate=true;}
    this.uranusMaterial=new THREE.MeshStandardMaterial({map:tex,bumpMap:bump,bumpScale:.004,roughness:.93,metalness:0,color:0xf2ffff});
    this.systemGroup=new THREE.Group();this.systemGroup.rotation.y=this.viewYaw;this.scene.add(this.systemGroup);this.axialGroup=new THREE.Group();this.axialGroup.rotation.z=THREE.MathUtils.degToRad(URANUS_TILT_DEG);this.systemGroup.add(this.axialGroup);
    this.planet=new THREE.Mesh(new THREE.SphereGeometry(1,160,112),this.uranusMaterial);this.planet.scale.y=.974;this.planet.rotation.y=this.renderedRotation;this.axialGroup.add(this.planet);
    const cloudMat=this.uranusMaterial.clone();cloudMat.transparent=true;cloudMat.opacity=.085;cloudMat.depthWrite=false;cloudMat.bumpMap=null;cloudMat.roughness=.98;this.cloudLayer=new THREE.Mesh(new THREE.SphereGeometry(1.008,128,90),cloudMat);this.cloudLayer.scale.y=.974;this.axialGroup.add(this.cloudLayer);
    const atmMat=new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:`varying vec3 vN;varying vec3 vW;void main(){vN=normalize(mat3(modelMatrix)*normal);vec4 w=modelMatrix*vec4(position,1.);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`precision highp float;varying vec3 vN;varying vec3 vW;void main(){vec3 V=normalize(cameraPosition-vW);float rim=pow(1.-max(dot(normalize(vN),V),0.),3.25);gl_FragColor=vec4(vec3(.34,.88,.94)*rim*.34,rim*.24);}`});this.atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.035,112,80),atmMat);this.atmosphere.scale.y=.974;this.axialGroup.add(this.atmosphere);
    this.ringGroup=this.createRingSystem(THREE);this.axialGroup.add(this.ringGroup);this.createSemanticObjects(THREE);this.createSaturnFallback(THREE);this.createStars(THREE);
    this.hemi=new THREE.HemisphereLight(0xc8f2f0,0x111922,.90);this.scene.add(this.hemi);this.key=new THREE.DirectionalLight(0xf0ffff,2.85);this.key.position.set(-4.6,3.3,5.6);this.scene.add(this.key);this.fill=new THREE.DirectionalLight(0x75b4d2,.40);this.fill.position.set(4,-1.2,2.4);this.scene.add(this.fill);
    canvas.addEventListener("webglcontextlost",e=>{e.preventDefault();this.createCanvasFallback();this.resize();if(this.active)this.render();},{once:true});this.mode="webgl";this.element.dataset.renderer="webgl";
  }
  createRingSystem(THREE){const g=new THREE.Group(),specs=[[1.31,1.34,.20,0x34454a],[1.40,1.425,.27,0x49595c],[1.49,1.515,.24,0x2d3e43],[1.59,1.625,.35,0x5a6868],[1.72,1.75,.19,0x36484b],[1.86,1.895,.32,0x667273],[2.04,2.075,.14,0x536164]];for(const [a,b,o,c] of specs){const m=new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,depthTest:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.NormalBlending});m.userData.baseOpacity=o;const ring=new THREE.Mesh(new THREE.RingGeometry(a,b,256,2),m);ring.rotation.x=Math.PI/2;ring.renderOrder=1;g.add(ring);}return g;}
  createSemanticObjects(THREE){
    this.magnetosphereGroup=new THREE.Group();const magMat=new THREE.LineBasicMaterial({color:0xb286d8,transparent:true,opacity:.38,depthWrite:false});for(const s of [1,1.25,1.52]){const pts=[];for(let i=0;i<120;i++){const a=i/120*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*2.0*s,Math.sin(a)*.70*s,0));}const geo=new THREE.BufferGeometry().setFromPoints(pts),line=new THREE.LineLoop(geo,magMat.clone());line.rotation.z=THREE.MathUtils.degToRad(58);line.position.x=.22;this.magnetosphereGroup.add(line);}this.magnetosphereGroup.visible=false;this.systemGroup.add(this.magnetosphereGroup);
    this.moonGroup=new THREE.Group();const makeMoon=(r,color,pos)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(r,48,32),new THREE.MeshStandardMaterial({color,roughness:1,metalness:0}));m.position.set(...pos);this.moonGroup.add(m);return m;};this.miranda=makeMoon(.19,0xa6afae,[2.2,.62,.15]);this.titania=makeMoon(.24,0xa6b3b0,[2.45,-.56,-.15]);this.oberon=makeMoon(.225,0x87938f,[-2.2,.48,.05]);this.moonGroup.visible=false;this.systemGroup.add(this.moonGroup);
  }
  createSaturnFallback(THREE){const m=new THREE.MeshStandardMaterial({color:0xd8c492,roughness:.92,metalness:0});if(this.saturnSurface){const t=new THREE.Texture(this.saturnSurface);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=THREE.RepeatWrapping;t.needsUpdate=true;m.map=t;}this.legacySaturnPlanet=new THREE.Mesh(new THREE.SphereGeometry(1,112,72),m);this.legacySaturnPlanet.scale.y=.905;this.legacySaturnGroup=new THREE.Group();this.legacySaturnGroup.rotation.set(-.28,0,-.14);this.legacySaturnGroup.add(this.legacySaturnPlanet);const rm=new THREE.MeshBasicMaterial({color:0xc7b68d,transparent:true,opacity:.55,depthTest:true,depthWrite:false,side:THREE.DoubleSide});const r=new THREE.Mesh(new THREE.RingGeometry(1.28,2.48,256,2),rm);r.rotation.x=Math.PI/2;this.legacySaturnGroup.add(r);this.scene.add(this.legacySaturnGroup);this.legacySaturnGroup.visible=false;this.travelSaturnGroup=this.legacySaturnGroup;this.travelSaturn=this.legacySaturnPlanet;}
  createStars(THREE){const count=this.mobile?350:700,positions=new Float32Array(count*3);for(let i=0;i<count;i++){const a=i*12.9898;positions[i*3]=(Math.sin(a)*.5)*34;positions[i*3+1]=(Math.sin(a*1.71+.3)*.5)*20;positions[i*3+2]=-4-Math.abs(Math.sin(a*2.11))*45;}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(positions,3));this.stars=new THREE.Points(g,new THREE.PointsMaterial({color:0xb7d0df,size:.025,transparent:true,opacity:.53,sizeAttenuation:true}));this.scene.add(this.stars);}
  createCanvasFallback(){this.renderer?.dispose?.();this.renderer=null;const c=document.createElement("canvas");this.canvas=c;this.ctx=c.getContext("2d");this.viewport.replaceChildren(c);this.mode="canvas";this.element.dataset.renderer="canvas";}
  resize(){const r=this.viewport.getBoundingClientRect();this.width=Math.max(1,Math.floor(r.width));this.height=Math.max(1,Math.floor(r.height));const wasMobile=this.mobile;this.mobile=this.width<=700||this.height>this.width*1.18;const dpr=Math.min(devicePixelRatio||1,this.mobile?1.5:2);if(this.mode==="webgl"&&this.renderer){this.renderer.setPixelRatio(dpr);this.renderer.setSize(this.width,this.height,false);this.camera.aspect=this.width/this.height;this.camera.updateProjectionMatrix();}else if(this.canvas){this.canvas.width=Math.max(1,Math.floor(this.width*dpr));this.canvas.height=Math.max(1,Math.floor(this.height*dpr));this.canvas.style.width=this.width+"px";this.canvas.style.height=this.height+"px";this.ctx.setTransform(dpr,0,0,dpr,0,0);}if(wasMobile!==this.mobile&&!this.travelMode&&!this.exploring){this.viewCameraZ=this.mobile?7.65:7.0;this.focusFrom.z=this.viewCameraZ;this.focusTo.z=this.viewCameraZ;}if(this.active)this.render();}
  suspendRenderForHandoff(){cancelAnimationFrame(this.frame);this.frame=null;}
  bindSaturnVisualSource(owner){this._saturnVisualOwner=owner||null;return Boolean(this._saturnVisualOwner);}
  _borrowSaturn({saturnRotation,saturnTime}={}){const o=this._saturnVisualOwner;if(!o||this.mode!=="webgl"||o.mode!=="webgl"||!this.scene||!o.planetGroup)return false;o.suspendRenderForHandoff?.();this.scene.add(o.planetGroup);this.travelSaturnGroup=o.planetGroup;this.travelSaturn=o.planet;this._borrowedSaturn=true;this._saturnStartRotation=Number.isFinite(saturnRotation)?saturnRotation:(o.planet?.rotation?.y??2.2);this._saturnTimeStart=Number.isFinite(saturnTime)?saturnTime:(o.time??8.5);this.travelSaturn.rotation.y=this._saturnStartRotation;this.legacySaturnGroup.visible=false;return true;}
  _releaseSaturn(){if(!this._borrowedSaturn)return;const o=this._saturnVisualOwner;this._saturnEndRotation=this.travelSaturn?.rotation.y??this._saturnStartRotation;this._saturnEndTime=this._saturnVisualTime??this._saturnTimeStart;if(o?.scene&&o?.planetGroup){o.scene.add(o.planetGroup);o.time=this._saturnEndTime;o.planet.rotation.y=this._saturnEndRotation;o.renderedRotation=this._saturnEndRotation;}this.travelSaturnGroup=this.legacySaturnGroup;this.travelSaturn=this.legacySaturnPlanet;this._borrowedSaturn=false;}
  getSaturnVisualRotation(){return Number.isFinite(this._saturnEndRotation)?this._saturnEndRotation:(this._saturnVisualOwner?.planet?.rotation?.y??2.2);} getSaturnVisualTime(){return Number.isFinite(this._saturnEndTime)?this._saturnEndTime:(this._saturnVisualOwner?.time??8.5);}
  start({settled=false,rotation=null,time=null}={}){this.active=true;this.travelMode=null;this.travelCallbacks={};this.time=Number.isFinite(time)?time:(settled?8.5:0);this.rotationBase=Number.isFinite(rotation)?rotation-this.time*.021:2.15;this.renderedRotation=this.rotationBase+this.time*.021;this.exploring=false;this.explorationBlend=this.explorationBlendTarget=0;this.element.hidden=false;this.element.style.opacity="1";this.element.classList.remove("is-exploring","is-leaving");this.caption.classList.remove("is-visible");this.caption.inert=true;this.exploration.inert=true;this.viewYaw=-.38;this.viewCameraZ=this.mobile?7.6:7.0;this.setExplorationStop(0,{immediate:true,announce:false});this.prepare();this.resize();cancelAnimationFrame(this.frame);this.previous=performance.now();this.tick(this.previous);}
  stop(){this.active=false;this.travelMode=null;this.travelCallbacks={};cancelAnimationFrame(this.frame);this.frame=null;this.element.hidden=true;this.element.style.opacity="0";this.element.classList.remove("is-exploring","is-leaving");this.exploring=false;this.caption.inert=true;this.exploration.inert=true;this.contextMedia.replaceChildren();this.contextMedia.hidden=true;this._releaseSaturn();}
  enterExploration(){if(!this.active||this.exploring||this.travelMode)return;this.exploring=true;this.explorationBlendTarget=1;this.element.classList.add("is-exploring");this.caption.inert=true;this.exploration.inert=false;this._applyTopicView(this.topicIndex,false);if(!this.frame){this.previous=performance.now();this.tick(this.previous);}document.getElementById("announcement").textContent=`Mode eksplorasi Uranus dimulai. ${URANUS_EXPLORATION_STOPS[this.topicIndex].title}.`;requestAnimationFrame(()=>this.topicTitle.focus({preventScroll:true}));}
  exitExploration(){if(!this.exploring)return;this.exploring=false;this.explorationBlendTarget=0;this.element.classList.remove("is-exploring");this.exploration.inert=true;this.caption.inert=false;this._beginFocus(-.38,this.mobile?7.6:7.0);this._setSemantic("identity");if(!this.frame){this.previous=performance.now();this.tick(this.previous);}document.getElementById("announcement").textContent="Kembali ke panorama Uranus.";requestAnimationFrame(()=>this.exploreButton.focus({preventScroll:true}));}
  setExplorationStop(index,{immediate=false,announce=true}={}){const prev=this.topicIndex??0,next=Math.max(0,Math.min(URANUS_EXPLORATION_STOPS.length-1,index)),stop=URANUS_EXPLORATION_STOPS[next];this.topicIndex=next;if(!immediate){this.exploration.classList.remove("is-switching-next","is-switching-prev");void this.exploration.offsetWidth;this.exploration.classList.add(next>=prev?"is-switching-next":"is-switching-prev");clearTimeout(this._switchTimer);this._switchTimer=setTimeout(()=>this.exploration.classList.remove("is-switching-next","is-switching-prev"),560);}this.topicKicker.textContent=stop.kicker;this.topicTitle.textContent=stop.title;this.topicSubtitle.textContent=stop.subtitle;this.topicSummary.textContent=stop.summary;this.topicFacts.replaceChildren(...stop.facts.map(f=>{const li=document.createElement("li");li.textContent=f;return li;}));this.topicSource.href=stop.source;this.topicCurrent.textContent=String(next+1).padStart(2,"0");this.topicPrev.disabled=next===0;this.topicNext.disabled=next===URANUS_EXPLORATION_STOPS.length-1;Array.from(this.topicProgress.children).forEach((bar,i)=>bar.classList.toggle("is-active",i===next));window.ExplorationMedia?.render?.("uranus",stop,this.contextMedia);this._applyTopicView(next,immediate||!this.exploring);if(this.active&&!this.frame){this.previous=performance.now();this.tick(this.previous);}if(announce&&this.exploring)document.getElementById("announcement").textContent=`Eksplorasi Uranus ${next+1} dari ${URANUS_EXPLORATION_STOPS.length}: ${stop.title}.`;}
  _applyTopicView(index,immediate=false){const stop=URANUS_EXPLORATION_STOPS[index],views=[[-.38,7.0],[-.18,7.25],[.08,7.35],[-.54,6.55],[-.34,7.15],[-.74,6.55],[.42,7.55],[-.28,7.55],[-.12,7.7],[-.45,7.05],[-.34,7.15]],v=views[index]||views[0];this._setSemantic(stop.semantic);if(immediate){this.viewYaw=v[0];this.viewCameraZ=this.mobile?v[1]+.65:v[1];this.focusState="FOCUSED_IDLE";this.focusProgress=1;}else this._beginFocus(v[0],this.mobile?v[1]+.65:v[1]);}
  _beginFocus(yaw,z){this.focusFrom={yaw:this.viewYaw,z:this.viewCameraZ};this.focusTo={yaw,z};this.focusProgress=0;this.focusState="FOCUS_TRANSITION";}
  _setSemantic(kind){this.semantic=kind;this.axisOverlay.hidden=!(kind==="axis"||kind==="seasons");this.seasonOverlay.hidden=kind!=="seasons";this.ringAnnotation.hidden=kind!=="rings";if(this.magnetosphereGroup)this.magnetosphereGroup.visible=kind==="magnetosphere";if(this.moonGroup){this.moonGroup.visible=kind==="miranda"||kind==="moons";this.miranda.visible=kind==="miranda";this.titania.visible=kind==="moons";this.oberon.visible=kind==="moons";}}
  _updateFocus(delta){if(this.focusState!=="FOCUS_TRANSITION")return;this.focusProgress=Math.min(1,this.focusProgress+delta/(this.motion.matches?.05:.95));const t=this.travelSmooth(this.focusProgress);this.viewYaw=this.focusFrom.yaw+(this.focusTo.yaw-this.focusFrom.yaw)*t;this.viewCameraZ=this.focusFrom.z+(this.focusTo.z-this.focusFrom.z)*t;if(this.focusProgress>=1)this.focusState="FOCUSED_IDLE";}
  beginTravelFromSaturn({onCovered,onComplete,saturnRotation=2.2,saturnTime=8.5,direction=1}={}){if(this.active&&this.travelMode)return;this.active=true;this.exploring=false;this.travelMode="from-saturn";this.travelDirection=direction>=0?1:-1;this.travelCallbacks={onCovered,onComplete};this.travelStartedAt=0;this.time=0;this.travelDuration=this.motion.matches?.55:8.3;this.travelCoveredFired=false;this.travelCompleteFired=false;this.element.hidden=false;this.element.style.opacity="1";this.element.classList.add("is-leaving");this.caption.classList.remove("is-visible");this.caption.inert=true;this.exploration.inert=true;if(this.mode==="pending"){this.surface=this.surface||this.makeFallbackSurface();this.createCanvasFallback();}this.prepare();this.resize();this._borrowSaturn({saturnRotation,saturnTime});if(this.travelSaturn)this.travelSaturn.rotation.y=saturnRotation;cancelAnimationFrame(this.frame);this.previous=performance.now();this.tick(this.previous);}
  beginTravelToSaturn({onCovered,onComplete,direction=-1}={}){if(!this.active||this.travelMode||this.exploring)return;this._borrowSaturn({saturnRotation:this._saturnVisualOwner?.planet?.rotation?.y,saturnTime:this._saturnVisualOwner?.time});this.travelMode="to-saturn";this.travelDirection=direction>=0?1:-1;this.travelCallbacks={onCovered,onComplete};this.travelStartedAt=this.time;this.travelDuration=this.motion.matches?.55:8.3;this.travelCoveredFired=false;this.travelCompleteFired=false;this.element.classList.add("is-leaving");this.caption.inert=true;if(!this.frame){this.previous=performance.now();this.tick(this.previous);}}
  tick(now){this.frame=null;if(!this.active||document.hidden)return;const d=Math.min((now-this.previous)/1000,.12);this.previous=now;this.time+=d;const damp=1-Math.exp(-d*2);this.cameraOffset.x+=(this.pointer.x-this.cameraOffset.x)*damp;this.cameraOffset.y+=(this.pointer.y-this.cameraOffset.y)*damp;const ed=this.motion.matches?1:1-Math.exp(-d*3);this.explorationBlend+=(this.explorationBlendTarget-this.explorationBlend)*ed;this._updateFocus(d);this.render();if(this.active&&!this.motion.matches)this.frame=requestAnimationFrame(t=>this.tick(t));else if(this.active&&(this.travelMode||this.focusState==="FOCUS_TRANSITION"||Math.abs(this.explorationBlend-this.explorationBlendTarget)>.002))this.frame=requestAnimationFrame(t=>this.tick(t));}
  render(){if(this.travelMode)this.renderTravel();else this.renderUranus();}
  renderUranus(){const blend=this.explorationBlend,x=this.mobile?0:(.72+blend*.08),y=this.mobile?(-.03-blend*.08):(.02+blend*.015),scale=this.mobile?.82:1.02;this.renderedRotation=this.rotationBase+this.time*.021;if(this.mode==="webgl"){this.systemGroup.visible=true;this.travelSaturnGroup.visible=false;this.systemGroup.position.set(x,y,0);this.systemGroup.scale.setScalar(scale);this.systemGroup.rotation.y=this.viewYaw;this.planet.rotation.y=this.renderedRotation;this.cloudLayer.rotation.y=this.renderedRotation+this.time*.003;const ringPulse=1+.025*Math.sin(this.time*.13);this.ringGroup.children.forEach(r=>r.material.opacity=r.material.userData.baseOpacity*ringPulse);this.camera.position.set(this.motion.matches?0:this.cameraOffset.x*.09,this.motion.matches?0:-this.cameraOffset.y*.06,this.viewCameraZ);this.camera.lookAt(0,0,0);this.renderer.render(this.scene,this.camera);}else this.drawCanvasUranus(x,y,scale);if(this.time>1.0&&!this.travelMode){this.caption.classList.add("is-visible");this.caption.inert=this.exploring;this.credit.style.opacity=this.exploring?"0":".88";}}
  renderTravel(){const s=this.travelState(),reverse=this.travelMode==="to-saturn",raw=this.clamp((this.time-this.travelStartedAt)/this.travelDuration),direction=this.travelDirection>=0?1:-1,aspect=this.camera?.aspect||this.width/this.height,half=Math.tan((34*Math.PI/180)/2)*7,separationMagnitude=half*aspect*(this.mobile?4.05:3.35),separation=separationMagnitude*direction,cameraX=separation*s.pan,cameraZ=7*(1+1.5*s.pullback*(1-s.approach)),uranusLane=reverse?0:separation,saturnLane=reverse?separation:0;const uX=this.mobile?0:.72,uY=this.mobile?-.03:.02,uScale=this.mobile?.82:1.02,sX=this.mobile?0:.66,sY=this.mobile?-.03:.015,sScale=this.mobile?.76:1.0;
    const sourceX=reverse?uX:sX,sourceExtent=reverse?2.05*uScale:2.45*sScale,viewHalfWidth=Math.tan(17*Math.PI/180)*cameraZ*aspect;
    const sourceDeparted=s.pullback>.98&&Math.abs(sourceX-cameraX)-sourceExtent>viewHalfWidth*1.01;
    this.travelLifecycle=sourceDeparted?"CURRENT_DEPARTED":(s.pan>.02?"LATERAL_TRAVEL":"RECEDING_CURRENT");if(s.approach>.04)this.travelLifecycle="APPROACHING_DESTINATION";if(s.approach>.90)this.travelLifecycle="SETTLING";
    if(this.mode==="webgl"){this.systemGroup.visible=reverse?!sourceDeparted:true;this.travelSaturnGroup.visible=reverse?true:!sourceDeparted;this.systemGroup.position.set(uranusLane+uX,uY,0);this.systemGroup.scale.setScalar(uScale);this.systemGroup.rotation.y=-.38;this.planet.rotation.y=this.rotationBase+this.time*.021;this.cloudLayer.rotation.y=this.planet.rotation.y+this.time*.003;
      const farFactor=this.clamp((cameraZ-7)/10.5);this.ringGroup.children.forEach(r=>r.material.opacity=r.material.userData.baseOpacity*(1+.42*farFactor));
      this.travelSaturnGroup.position.set(saturnLane+sX,sY,0);this.travelSaturnGroup.scale.setScalar(sScale);if(!this._borrowedSaturn){this.travelSaturnGroup.rotation.set(-.28,0,-.14);}const elapsed=Math.max(0,this.time-this.travelStartedAt),visualTime=this._saturnTimeStart+elapsed,rotation=this._saturnStartRotation+elapsed*.026;this._saturnVisualTime=visualTime;this.travelSaturn.rotation.y=rotation;const o=this._saturnVisualOwner;if(o?.ring?.material?.uniforms?.uTime)o.ring.material.uniforms.uTime.value=visualTime;if(o?.cloudLayer)o.cloudLayer.rotation.y=rotation+visualTime*.0035;
      if(this.stars)this.stars.position.x=cameraX*.94;this.camera.position.set(cameraX,0,cameraZ);const lookOffset=Math.sin(s.pan*Math.PI)*separationMagnitude*.055*direction;this.camera.lookAt(cameraX+lookOffset,0,0);this.renderer.render(this.scene,this.camera);
    }else this.drawCanvasTravel(s,reverse,direction,sourceDeparted);
    if(!this.travelCoveredFired&&raw>=.11){this.travelCoveredFired=true;this.travelCallbacks.onCovered?.();}
    if(raw>=.999&&!this.travelCompleteFired){this.travelCompleteFired=true;const cb=this.travelCallbacks.onComplete;this._releaseSaturn();if(!reverse){this.travelMode=null;this.travelCallbacks={};this.element.classList.remove("is-leaving");this.caption.classList.add("is-visible");this.caption.inert=false;this.credit.style.opacity=".88";document.getElementById("announcement").textContent="Tiba di Uranus.";}cb?.();}
  }
  drawCanvasUranus(x,y,scale,{clear=true}={}){const c=this.ctx;if(!c)return;if(clear){c.clearRect(0,0,this.width,this.height);this.drawCanvasStars(c,0);}const cx=this.width*(.5+x*.09),cy=this.height*(.48-y*.06),r=Math.min(this.width,this.height)*(this.mobile?.18:.20)*scale;c.save();c.translate(cx,cy);c.rotate(-.28);c.strokeStyle="rgba(62,82,87,.58)";c.lineWidth=Math.max(1,r*.025);for(const k of [1.35,1.52,1.72,1.92]){c.beginPath();c.ellipse(0,0,r*k,r*k*.27,0,0,Math.PI*2);c.stroke();}c.restore();c.save();c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.clip();c.drawImage(this.surface,0,0,this.surface.width,this.surface.height,cx-r,cy-r,r*2,r*2);c.restore();c.save();c.translate(cx,cy);c.rotate(-.28);c.strokeStyle="rgba(83,104,108,.68)";c.lineWidth=Math.max(1,r*.022);for(const k of [1.35,1.52,1.72,1.92]){c.beginPath();c.ellipse(0,0,r*k,r*k*.27,0,0,Math.PI);c.stroke();}c.restore();const g=c.createRadialGradient(cx-r*.32,cy-r*.28,r*.15,cx,cy,r*1.08);g.addColorStop(0,"rgba(225,255,252,.1)");g.addColorStop(.72,"rgba(63,134,150,.06)");g.addColorStop(1,"rgba(3,8,16,.56)");c.fillStyle=g;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();}
  drawCanvasStars(c,offset){c.fillStyle="#a9c5d2";for(let i=0;i<140;i++){const x=((i*137.5+offset*31)%this.width+this.width)%this.width,y=(i*83.7)%this.height;c.globalAlpha=.18+(i%5)*.08;c.fillRect(x,y,1,1);}c.globalAlpha=1;}
  drawCanvasTravel(s,reverse,direction,sourceDeparted=false){const c=this.ctx;if(!c)return;c.clearRect(0,0,this.width,this.height);const shift=this.width*.34*s.pan*direction;this.drawCanvasStars(c,-shift*.15);let uAlpha=reverse?1-s.progress:s.progress,sAlpha=reverse?s.progress:1-s.progress;if(sourceDeparted){if(reverse)uAlpha=0;else sAlpha=0;}c.save();c.globalAlpha=uAlpha>0?Math.max(.12,uAlpha):0;c.translate(reverse?-shift:shift,0);if(uAlpha>0)this.drawCanvasUranus(0,0,.55+.45*uAlpha,{clear:false});c.restore();c.globalAlpha=sAlpha>0?Math.max(.12,sAlpha):0;const cx=this.width*.5+(reverse?shift:-shift),cy=this.height*.48,r=Math.min(this.width,this.height)*(.16+.07*sAlpha);if(sAlpha>0){c.fillStyle="#d4c08e";c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.strokeStyle="rgba(215,198,153,.62)";c.lineWidth=2;c.beginPath();c.ellipse(cx,cy,r*2.3,r*.55,-.14,0,Math.PI*2);c.stroke();}c.globalAlpha=1;}
};
