const {chromium}=require('playwright'),assert=require('assert'),{spawn}=require('child_process');
(async()=>{const root=require('path').resolve(__dirname,'..');require('fs').mkdirSync(root+'/.tmp',{recursive:true});process.chdir(root+'/.tmp');const server=spawn('python',['-m','http.server','8780','--directory',root]);const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE || undefined,args:['--no-sandbox','--enable-unsafe-swiftshader'],headless:true});try{
const p=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8780');await p.evaluate(async()=>{await Promise.all([earth.prepare(),mars.prepare()]);mission.classList.add('is-earth');phase='earth';document.querySelector('.intro').inert=true;earth.start({settled:true})});await p.click('#earth-explore-button');
async function check(prefix,i){await p.evaluate(({prefix,i})=>(prefix==='earth'?earth:mars).setExplorationStop(i),{prefix,i});await p.waitForFunction(prefix=>{let im=document.querySelector(`#${prefix}-topic-media img`);return im&&im.complete&&im.naturalWidth>0},prefix);assert(await p.locator(`#${prefix}-topic-media img`).getAttribute('alt'));}
for(let i=4;i<11;i++)await check('earth',i);
await p.screenshot({path:'media-earth-desktop.png'});
async function sizes(prefix){for(const v of [{width:1366,height:600},{width:390,height:844},{width:375,height:667}]){await p.setViewportSize(v);await p.waitForTimeout(300);const b=await p.evaluate(prefix=>{const c=document.getElementById(prefix+'-exploration').getBoundingClientRect(),s=document.getElementById(prefix+'-topic-scroll'),n=document.getElementById(prefix+'-topic-next').getBoundingClientRect(),src=document.getElementById(prefix+'-topic-source').getBoundingClientRect();s.scrollTop=9999;return {top:c.top,bottom:c.bottom,h:innerHeight,scroll:s.scrollTop,height:s.clientHeight,nav:n.bottom,source:src.bottom}},prefix);assert(b.top>=0&&b.bottom<=b.h&&b.scroll>0&&b.height>20&&b.nav<=b.h&&b.source<=b.h,JSON.stringify(b));await p.evaluate(prefix=>document.getElementById(prefix+'-topic-scroll').scrollTop=0,prefix);await p.screenshot({path:`media-${prefix}-${v.width}.png`});console.log(prefix,v,b)}}
await sizes('earth');await p.setViewportSize({width:1440,height:900});await p.click('#earth-exploration-close');await p.click('#earth-next');await p.waitForFunction(()=>phase==='mars');await p.click('#mars-explore-button');for(let i=0;i<6;i++)await check('mars',i);await p.screenshot({path:'media-mars-desktop.png'});await sizes('mars');
await p.evaluate(()=>{mars.setExplorationStop(0);mars.setExplorationStop(2);mars.setExplorationStop(5)});await p.waitForFunction(()=>document.querySelector('#mars-topic-media img').complete);assert((await p.locator('#mars-topic-media img').getAttribute('src')).includes('dust-storm'));
await p.evaluate(()=>ExplorationMedia.render('mars',{...MARS_EXPLORATION_STOPS[5],image:'assets/missing-test.webp'}));await p.waitForFunction(()=>document.querySelector('#mars-topic-media img').hidden);assert((await p.locator('#mars-topic-media').textContent()).includes('Gambar tidak tersedia'));await check('mars',0);
await p.setViewportSize({width:1440,height:900});await p.click('#mars-exploration-close');await p.click('#mars-prev-planet');await p.waitForFunction(()=>phase==='earth');await p.click('#earth-explore-button');await p.locator('#earth-topic-progress button').nth(0).click();assert(await p.locator('#earth-topic-media').isHidden());await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#earth-topic-progress button').nth(10).click();await p.waitForTimeout(2000);assert.equal(await p.locator('#earth-marker-country').textContent(),'India');assert.equal(await p.evaluate(()=>earth.marker.style.opacity),'0.9');assert.deepEqual(errors,[]);console.log('PASS all 13 images, alt, responsive cards, source/nav, scroll, rapid switching, failure/recovery, Earth/Mars travel, annotation and rotation.');
}finally{await browser.close();server.kill()}})().catch(e=>{console.error(e);process.exit(1)});
